
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  Session: 'Session',
  Server: 'Server',
  ServerMember: 'ServerMember',
  Role: 'Role',
  Category: 'Category',
  Channel: 'Channel',
  Message: 'Message',
  Attachment: 'Attachment',
  PMChannel: 'PMChannel',
  PrivateMessage: 'PrivateMessage',
  Friend: 'Friend'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  username: 'username',
  email: 'email',
  passwordHash: 'passwordHash',
  avatarUrl: 'avatarUrl',
  emailVerified: 'emailVerified',
  bot: 'bot',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const SessionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  token: 'token',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent'
} as const

export type SessionScalarFieldEnum = (typeof SessionScalarFieldEnum)[keyof typeof SessionScalarFieldEnum]


export const ServerScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  iconUrl: 'iconUrl',
  ownerId: 'ownerId',
  inviteCode: 'inviteCode',
  public: 'public',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ServerScalarFieldEnum = (typeof ServerScalarFieldEnum)[keyof typeof ServerScalarFieldEnum]


export const ServerMemberScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  serverId: 'serverId',
  nickname: 'nickname',
  joinedAt: 'joinedAt'
} as const

export type ServerMemberScalarFieldEnum = (typeof ServerMemberScalarFieldEnum)[keyof typeof ServerMemberScalarFieldEnum]


export const RoleScalarFieldEnum = {
  id: 'id',
  serverId: 'serverId',
  name: 'name',
  color: 'color',
  permissions: 'permissions',
  position: 'position',
  mentionable: 'mentionable',
  createdAt: 'createdAt'
} as const

export type RoleScalarFieldEnum = (typeof RoleScalarFieldEnum)[keyof typeof RoleScalarFieldEnum]


export const CategoryScalarFieldEnum = {
  id: 'id',
  serverId: 'serverId',
  name: 'name',
  position: 'position'
} as const

export type CategoryScalarFieldEnum = (typeof CategoryScalarFieldEnum)[keyof typeof CategoryScalarFieldEnum]


export const ChannelScalarFieldEnum = {
  id: 'id',
  serverId: 'serverId',
  categoryId: 'categoryId',
  name: 'name',
  type: 'type',
  topic: 'topic',
  position: 'position',
  slowMode: 'slowMode',
  nsfw: 'nsfw',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ChannelScalarFieldEnum = (typeof ChannelScalarFieldEnum)[keyof typeof ChannelScalarFieldEnum]


export const MessageScalarFieldEnum = {
  id: 'id',
  channelId: 'channelId',
  authorId: 'authorId',
  content: 'content',
  type: 'type',
  replyToId: 'replyToId',
  edited: 'edited',
  editedAt: 'editedAt',
  deletedAt: 'deletedAt',
  createdAt: 'createdAt'
} as const

export type MessageScalarFieldEnum = (typeof MessageScalarFieldEnum)[keyof typeof MessageScalarFieldEnum]


export const AttachmentScalarFieldEnum = {
  id: 'id',
  messageId: 'messageId',
  url: 'url',
  filename: 'filename',
  size: 'size',
  mimeType: 'mimeType',
  width: 'width',
  height: 'height'
} as const

export type AttachmentScalarFieldEnum = (typeof AttachmentScalarFieldEnum)[keyof typeof AttachmentScalarFieldEnum]


export const PMChannelScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt'
} as const

export type PMChannelScalarFieldEnum = (typeof PMChannelScalarFieldEnum)[keyof typeof PMChannelScalarFieldEnum]


export const PrivateMessageScalarFieldEnum = {
  id: 'id',
  channelId: 'channelId',
  authorId: 'authorId',
  content: 'content',
  editedAt: 'editedAt',
  deletedAt: 'deletedAt',
  createdAt: 'createdAt'
} as const

export type PrivateMessageScalarFieldEnum = (typeof PrivateMessageScalarFieldEnum)[keyof typeof PrivateMessageScalarFieldEnum]


export const FriendScalarFieldEnum = {
  id: 'id',
  requesterId: 'requesterId',
  receiverId: 'receiverId',
  accepted: 'accepted',
  createdAt: 'createdAt'
} as const

export type FriendScalarFieldEnum = (typeof FriendScalarFieldEnum)[keyof typeof FriendScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

