
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const ChannelType = {
  TEXT: 'TEXT',
  VOICE: 'VOICE'
} as const

export type ChannelType = (typeof ChannelType)[keyof typeof ChannelType]


export const MessageType = {
  DEFAULT: 'DEFAULT',
  SYSTEM: 'SYSTEM',
  REPLY: 'REPLY'
} as const

export type MessageType = (typeof MessageType)[keyof typeof MessageType]
