
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Message` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Message
 * 
 */
export type MessageModel = runtime.Types.Result.DefaultSelection<Prisma.$MessagePayload>

export type AggregateMessage = {
  _count: MessageCountAggregateOutputType | null
  _min: MessageMinAggregateOutputType | null
  _max: MessageMaxAggregateOutputType | null
}

export type MessageMinAggregateOutputType = {
  id: string | null
  channelId: string | null
  authorId: string | null
  content: string | null
  type: $Enums.MessageType | null
  replyToId: string | null
  edited: boolean | null
  editedAt: Date | null
  deletedAt: Date | null
  createdAt: Date | null
}

export type MessageMaxAggregateOutputType = {
  id: string | null
  channelId: string | null
  authorId: string | null
  content: string | null
  type: $Enums.MessageType | null
  replyToId: string | null
  edited: boolean | null
  editedAt: Date | null
  deletedAt: Date | null
  createdAt: Date | null
}

export type MessageCountAggregateOutputType = {
  id: number
  channelId: number
  authorId: number
  content: number
  type: number
  replyToId: number
  edited: number
  editedAt: number
  deletedAt: number
  createdAt: number
  _all: number
}


export type MessageMinAggregateInputType = {
  id?: true
  channelId?: true
  authorId?: true
  content?: true
  type?: true
  replyToId?: true
  edited?: true
  editedAt?: true
  deletedAt?: true
  createdAt?: true
}

export type MessageMaxAggregateInputType = {
  id?: true
  channelId?: true
  authorId?: true
  content?: true
  type?: true
  replyToId?: true
  edited?: true
  editedAt?: true
  deletedAt?: true
  createdAt?: true
}

export type MessageCountAggregateInputType = {
  id?: true
  channelId?: true
  authorId?: true
  content?: true
  type?: true
  replyToId?: true
  edited?: true
  editedAt?: true
  deletedAt?: true
  createdAt?: true
  _all?: true
}

export type MessageAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Message to aggregate.
   */
  where?: Prisma.MessageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Messages to fetch.
   */
  orderBy?: Prisma.MessageOrderByWithRelationInput | Prisma.MessageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MessageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Messages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Messages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Messages
  **/
  _count?: true | MessageCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MessageMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MessageMaxAggregateInputType
}

export type GetMessageAggregateType<T extends MessageAggregateArgs> = {
      [P in keyof T & keyof AggregateMessage]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMessage[P]>
    : Prisma.GetScalarType<T[P], AggregateMessage[P]>
}




export type MessageGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MessageWhereInput
  orderBy?: Prisma.MessageOrderByWithAggregationInput | Prisma.MessageOrderByWithAggregationInput[]
  by: Prisma.MessageScalarFieldEnum[] | Prisma.MessageScalarFieldEnum
  having?: Prisma.MessageScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MessageCountAggregateInputType | true
  _min?: MessageMinAggregateInputType
  _max?: MessageMaxAggregateInputType
}

export type MessageGroupByOutputType = {
  id: string
  channelId: string
  authorId: string
  content: string
  type: $Enums.MessageType
  replyToId: string | null
  edited: boolean
  editedAt: Date | null
  deletedAt: Date | null
  createdAt: Date
  _count: MessageCountAggregateOutputType | null
  _min: MessageMinAggregateOutputType | null
  _max: MessageMaxAggregateOutputType | null
}

export type GetMessageGroupByPayload<T extends MessageGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MessageGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MessageGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MessageGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MessageGroupByOutputType[P]>
      }
    >
  >



export type MessageWhereInput = {
  AND?: Prisma.MessageWhereInput | Prisma.MessageWhereInput[]
  OR?: Prisma.MessageWhereInput[]
  NOT?: Prisma.MessageWhereInput | Prisma.MessageWhereInput[]
  id?: Prisma.StringFilter<"Message"> | string
  channelId?: Prisma.StringFilter<"Message"> | string
  authorId?: Prisma.StringFilter<"Message"> | string
  content?: Prisma.StringFilter<"Message"> | string
  type?: Prisma.EnumMessageTypeFilter<"Message"> | $Enums.MessageType
  replyToId?: Prisma.StringNullableFilter<"Message"> | string | null
  edited?: Prisma.BoolFilter<"Message"> | boolean
  editedAt?: Prisma.DateTimeNullableFilter<"Message"> | Date | string | null
  deletedAt?: Prisma.DateTimeNullableFilter<"Message"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"Message"> | Date | string
  channel?: Prisma.XOR<Prisma.ChannelScalarRelationFilter, Prisma.ChannelWhereInput>
  author?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  replyTo?: Prisma.XOR<Prisma.MessageNullableScalarRelationFilter, Prisma.MessageWhereInput> | null
  replies?: Prisma.MessageListRelationFilter
  attachments?: Prisma.AttachmentListRelationFilter
}

export type MessageOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  content?: Prisma.SortOrder
  type?: Prisma.SortOrder
  replyToId?: Prisma.SortOrderInput | Prisma.SortOrder
  edited?: Prisma.SortOrder
  editedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  channel?: Prisma.ChannelOrderByWithRelationInput
  author?: Prisma.UserOrderByWithRelationInput
  replyTo?: Prisma.MessageOrderByWithRelationInput
  replies?: Prisma.MessageOrderByRelationAggregateInput
  attachments?: Prisma.AttachmentOrderByRelationAggregateInput
}

export type MessageWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.MessageWhereInput | Prisma.MessageWhereInput[]
  OR?: Prisma.MessageWhereInput[]
  NOT?: Prisma.MessageWhereInput | Prisma.MessageWhereInput[]
  channelId?: Prisma.StringFilter<"Message"> | string
  authorId?: Prisma.StringFilter<"Message"> | string
  content?: Prisma.StringFilter<"Message"> | string
  type?: Prisma.EnumMessageTypeFilter<"Message"> | $Enums.MessageType
  replyToId?: Prisma.StringNullableFilter<"Message"> | string | null
  edited?: Prisma.BoolFilter<"Message"> | boolean
  editedAt?: Prisma.DateTimeNullableFilter<"Message"> | Date | string | null
  deletedAt?: Prisma.DateTimeNullableFilter<"Message"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"Message"> | Date | string
  channel?: Prisma.XOR<Prisma.ChannelScalarRelationFilter, Prisma.ChannelWhereInput>
  author?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  replyTo?: Prisma.XOR<Prisma.MessageNullableScalarRelationFilter, Prisma.MessageWhereInput> | null
  replies?: Prisma.MessageListRelationFilter
  attachments?: Prisma.AttachmentListRelationFilter
}, "id">

export type MessageOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  content?: Prisma.SortOrder
  type?: Prisma.SortOrder
  replyToId?: Prisma.SortOrderInput | Prisma.SortOrder
  edited?: Prisma.SortOrder
  editedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.MessageCountOrderByAggregateInput
  _max?: Prisma.MessageMaxOrderByAggregateInput
  _min?: Prisma.MessageMinOrderByAggregateInput
}

export type MessageScalarWhereWithAggregatesInput = {
  AND?: Prisma.MessageScalarWhereWithAggregatesInput | Prisma.MessageScalarWhereWithAggregatesInput[]
  OR?: Prisma.MessageScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MessageScalarWhereWithAggregatesInput | Prisma.MessageScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Message"> | string
  channelId?: Prisma.StringWithAggregatesFilter<"Message"> | string
  authorId?: Prisma.StringWithAggregatesFilter<"Message"> | string
  content?: Prisma.StringWithAggregatesFilter<"Message"> | string
  type?: Prisma.EnumMessageTypeWithAggregatesFilter<"Message"> | $Enums.MessageType
  replyToId?: Prisma.StringNullableWithAggregatesFilter<"Message"> | string | null
  edited?: Prisma.BoolWithAggregatesFilter<"Message"> | boolean
  editedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Message"> | Date | string | null
  deletedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Message"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Message"> | Date | string
}

export type MessageCreateInput = {
  id?: string
  content: string
  type?: $Enums.MessageType
  edited?: boolean
  editedAt?: Date | string | null
  deletedAt?: Date | string | null
  createdAt?: Date | string
  channel: Prisma.ChannelCreateNestedOneWithoutMessagesInput
  author: Prisma.UserCreateNestedOneWithoutMessagesInput
  replyTo?: Prisma.MessageCreateNestedOneWithoutRepliesInput
  replies?: Prisma.MessageCreateNestedManyWithoutReplyToInput
  attachments?: Prisma.AttachmentCreateNestedManyWithoutMessageInput
}

export type MessageUncheckedCreateInput = {
  id?: string
  channelId: string
  authorId: string
  content: string
  type?: $Enums.MessageType
  replyToId?: string | null
  edited?: boolean
  editedAt?: Date | string | null
  deletedAt?: Date | string | null
  createdAt?: Date | string
  replies?: Prisma.MessageUncheckedCreateNestedManyWithoutReplyToInput
  attachments?: Prisma.AttachmentUncheckedCreateNestedManyWithoutMessageInput
}

export type MessageUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumMessageTypeFieldUpdateOperationsInput | $Enums.MessageType
  edited?: Prisma.BoolFieldUpdateOperationsInput | boolean
  editedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  channel?: Prisma.ChannelUpdateOneRequiredWithoutMessagesNestedInput
  author?: Prisma.UserUpdateOneRequiredWithoutMessagesNestedInput
  replyTo?: Prisma.MessageUpdateOneWithoutRepliesNestedInput
  replies?: Prisma.MessageUpdateManyWithoutReplyToNestedInput
  attachments?: Prisma.AttachmentUpdateManyWithoutMessageNestedInput
}

export type MessageUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumMessageTypeFieldUpdateOperationsInput | $Enums.MessageType
  replyToId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  edited?: Prisma.BoolFieldUpdateOperationsInput | boolean
  editedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  replies?: Prisma.MessageUncheckedUpdateManyWithoutReplyToNestedInput
  attachments?: Prisma.AttachmentUncheckedUpdateManyWithoutMessageNestedInput
}

export type MessageCreateManyInput = {
  id?: string
  channelId: string
  authorId: string
  content: string
  type?: $Enums.MessageType
  replyToId?: string | null
  edited?: boolean
  editedAt?: Date | string | null
  deletedAt?: Date | string | null
  createdAt?: Date | string
}

export type MessageUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumMessageTypeFieldUpdateOperationsInput | $Enums.MessageType
  edited?: Prisma.BoolFieldUpdateOperationsInput | boolean
  editedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MessageUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumMessageTypeFieldUpdateOperationsInput | $Enums.MessageType
  replyToId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  edited?: Prisma.BoolFieldUpdateOperationsInput | boolean
  editedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MessageListRelationFilter = {
  every?: Prisma.MessageWhereInput
  some?: Prisma.MessageWhereInput
  none?: Prisma.MessageWhereInput
}

export type MessageOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type MessageNullableScalarRelationFilter = {
  is?: Prisma.MessageWhereInput | null
  isNot?: Prisma.MessageWhereInput | null
}

export type MessageCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  content?: Prisma.SortOrder
  type?: Prisma.SortOrder
  replyToId?: Prisma.SortOrder
  edited?: Prisma.SortOrder
  editedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type MessageMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  content?: Prisma.SortOrder
  type?: Prisma.SortOrder
  replyToId?: Prisma.SortOrder
  edited?: Prisma.SortOrder
  editedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type MessageMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  content?: Prisma.SortOrder
  type?: Prisma.SortOrder
  replyToId?: Prisma.SortOrder
  edited?: Prisma.SortOrder
  editedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type MessageScalarRelationFilter = {
  is?: Prisma.MessageWhereInput
  isNot?: Prisma.MessageWhereInput
}

export type MessageCreateNestedManyWithoutAuthorInput = {
  create?: Prisma.XOR<Prisma.MessageCreateWithoutAuthorInput, Prisma.MessageUncheckedCreateWithoutAuthorInput> | Prisma.MessageCreateWithoutAuthorInput[] | Prisma.MessageUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?: Prisma.MessageCreateOrConnectWithoutAuthorInput | Prisma.MessageCreateOrConnectWithoutAuthorInput[]
  createMany?: Prisma.MessageCreateManyAuthorInputEnvelope
  connect?: Prisma.MessageWhereUniqueInput | Prisma.MessageWhereUniqueInput[]
}

export type MessageUncheckedCreateNestedManyWithoutAuthorInput = {
  create?: Prisma.XOR<Prisma.MessageCreateWithoutAuthorInput, Prisma.MessageUncheckedCreateWithoutAuthorInput> | Prisma.MessageCreateWithoutAuthorInput[] | Prisma.MessageUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?: Prisma.MessageCreateOrConnectWithoutAuthorInput | Prisma.MessageCreateOrConnectWithoutAuthorInput[]
  createMany?: Prisma.MessageCreateManyAuthorInputEnvelope
  connect?: Prisma.MessageWhereUniqueInput | Prisma.MessageWhereUniqueInput[]
}

export type MessageUpdateManyWithoutAuthorNestedInput = {
  create?: Prisma.XOR<Prisma.MessageCreateWithoutAuthorInput, Prisma.MessageUncheckedCreateWithoutAuthorInput> | Prisma.MessageCreateWithoutAuthorInput[] | Prisma.MessageUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?: Prisma.MessageCreateOrConnectWithoutAuthorInput | Prisma.MessageCreateOrConnectWithoutAuthorInput[]
  upsert?: Prisma.MessageUpsertWithWhereUniqueWithoutAuthorInput | Prisma.MessageUpsertWithWhereUniqueWithoutAuthorInput[]
  createMany?: Prisma.MessageCreateManyAuthorInputEnvelope
  set?: Prisma.MessageWhereUniqueInput | Prisma.MessageWhereUniqueInput[]
  disconnect?: Prisma.MessageWhereUniqueInput | Prisma.MessageWhereUniqueInput[]
  delete?: Prisma.MessageWhereUniqueInput | Prisma.MessageWhereUniqueInput[]
  connect?: Prisma.MessageWhereUniqueInput | Prisma.MessageWhereUniqueInput[]
  update?: Prisma.MessageUpdateWithWhereUniqueWithoutAuthorInput | Prisma.MessageUpdateWithWhereUniqueWithoutAuthorInput[]
  updateMany?: Prisma.MessageUpdateManyWithWhereWithoutAuthorInput | Prisma.MessageUpdateManyWithWhereWithoutAuthorInput[]
  deleteMany?: Prisma.MessageScalarWhereInput | Prisma.MessageScalarWhereInput[]
}

export type MessageUncheckedUpdateManyWithoutAuthorNestedInput = {
  create?: Prisma.XOR<Prisma.MessageCreateWithoutAuthorInput, Prisma.MessageUncheckedCreateWithoutAuthorInput> | Prisma.MessageCreateWithoutAuthorInput[] | Prisma.MessageUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?: Prisma.MessageCreateOrConnectWithoutAuthorInput | Prisma.MessageCreateOrConnectWithoutAuthorInput[]
  upsert?: Prisma.MessageUpsertWithWhereUniqueWithoutAuthorInput | Prisma.MessageUpsertWithWhereUniqueWithoutAuthorInput[]
  createMany?: Prisma.MessageCreateManyAuthorInputEnvelope
  set?: Prisma.MessageWhereUniqueInput | Prisma.MessageWhereUniqueInput[]
  disconnect?: Prisma.MessageWhereUniqueInput | Prisma.MessageWhereUniqueInput[]
  delete?: Prisma.MessageWhereUniqueInput | Prisma.MessageWhereUniqueInput[]
  connect?: Prisma.MessageWhereUniqueInput | Prisma.MessageWhereUniqueInput[]
  update?: Prisma.MessageUpdateWithWhereUniqueWithoutAuthorInput | Prisma.MessageUpdateWithWhereUniqueWithoutAuthorInput[]
  updateMany?: Prisma.MessageUpdateManyWithWhereWithoutAuthorInput | Prisma.MessageUpdateManyWithWhereWithoutAuthorInput[]
  deleteMany?: Prisma.MessageScalarWhereInput | Prisma.MessageScalarWhereInput[]
}

export type MessageCreateNestedManyWithoutChannelInput = {
  create?: Prisma.XOR<Prisma.MessageCreateWithoutChannelInput, Prisma.MessageUncheckedCreateWithoutChannelInput> | Prisma.MessageCreateWithoutChannelInput[] | Prisma.MessageUncheckedCreateWithoutChannelInput[]
  connectOrCreate?: Prisma.MessageCreateOrConnectWithoutChannelInput | Prisma.MessageCreateOrConnectWithoutChannelInput[]
  createMany?: Prisma.MessageCreateManyChannelInputEnvelope
  connect?: Prisma.MessageWhereUniqueInput | Prisma.MessageWhereUniqueInput[]
}

export type MessageUncheckedCreateNestedManyWithoutChannelInput = {
  create?: Prisma.XOR<Prisma.MessageCreateWithoutChannelInput, Prisma.MessageUncheckedCreateWithoutChannelInput> | Prisma.MessageCreateWithoutChannelInput[] | Prisma.MessageUncheckedCreateWithoutChannelInput[]
  connectOrCreate?: Prisma.MessageCreateOrConnectWithoutChannelInput | Prisma.MessageCreateOrConnectWithoutChannelInput[]
  createMany?: Prisma.MessageCreateManyChannelInputEnvelope
  connect?: Prisma.MessageWhereUniqueInput | Prisma.MessageWhereUniqueInput[]
}

export type MessageUpdateManyWithoutChannelNestedInput = {
  create?: Prisma.XOR<Prisma.MessageCreateWithoutChannelInput, Prisma.MessageUncheckedCreateWithoutChannelInput> | Prisma.MessageCreateWithoutChannelInput[] | Prisma.MessageUncheckedCreateWithoutChannelInput[]
  connectOrCreate?: Prisma.MessageCreateOrConnectWithoutChannelInput | Prisma.MessageCreateOrConnectWithoutChannelInput[]
  upsert?: Prisma.MessageUpsertWithWhereUniqueWithoutChannelInput | Prisma.MessageUpsertWithWhereUniqueWithoutChannelInput[]
  createMany?: Prisma.MessageCreateManyChannelInputEnvelope
  set?: Prisma.MessageWhereUniqueInput | Prisma.MessageWhereUniqueInput[]
  disconnect?: Prisma.MessageWhereUniqueInput | Prisma.MessageWhereUniqueInput[]
  delete?: Prisma.MessageWhereUniqueInput | Prisma.MessageWhereUniqueInput[]
  connect?: Prisma.MessageWhereUniqueInput | Prisma.MessageWhereUniqueInput[]
  update?: Prisma.MessageUpdateWithWhereUniqueWithoutChannelInput | Prisma.MessageUpdateWithWhereUniqueWithoutChannelInput[]
  updateMany?: Prisma.MessageUpdateManyWithWhereWithoutChannelInput | Prisma.MessageUpdateManyWithWhereWithoutChannelInput[]
  deleteMany?: Prisma.MessageScalarWhereInput | Prisma.MessageScalarWhereInput[]
}

export type MessageUncheckedUpdateManyWithoutChannelNestedInput = {
  create?: Prisma.XOR<Prisma.MessageCreateWithoutChannelInput, Prisma.MessageUncheckedCreateWithoutChannelInput> | Prisma.MessageCreateWithoutChannelInput[] | Prisma.MessageUncheckedCreateWithoutChannelInput[]
  connectOrCreate?: Prisma.MessageCreateOrConnectWithoutChannelInput | Prisma.MessageCreateOrConnectWithoutChannelInput[]
  upsert?: Prisma.MessageUpsertWithWhereUniqueWithoutChannelInput | Prisma.MessageUpsertWithWhereUniqueWithoutChannelInput[]
  createMany?: Prisma.MessageCreateManyChannelInputEnvelope
  set?: Prisma.MessageWhereUniqueInput | Prisma.MessageWhereUniqueInput[]
  disconnect?: Prisma.MessageWhereUniqueInput | Prisma.MessageWhereUniqueInput[]
  delete?: Prisma.MessageWhereUniqueInput | Prisma.MessageWhereUniqueInput[]
  connect?: Prisma.MessageWhereUniqueInput | Prisma.MessageWhereUniqueInput[]
  update?: Prisma.MessageUpdateWithWhereUniqueWithoutChannelInput | Prisma.MessageUpdateWithWhereUniqueWithoutChannelInput[]
  updateMany?: Prisma.MessageUpdateManyWithWhereWithoutChannelInput | Prisma.MessageUpdateManyWithWhereWithoutChannelInput[]
  deleteMany?: Prisma.MessageScalarWhereInput | Prisma.MessageScalarWhereInput[]
}

export type MessageCreateNestedOneWithoutRepliesInput = {
  create?: Prisma.XOR<Prisma.MessageCreateWithoutRepliesInput, Prisma.MessageUncheckedCreateWithoutRepliesInput>
  connectOrCreate?: Prisma.MessageCreateOrConnectWithoutRepliesInput
  connect?: Prisma.MessageWhereUniqueInput
}

export type MessageCreateNestedManyWithoutReplyToInput = {
  create?: Prisma.XOR<Prisma.MessageCreateWithoutReplyToInput, Prisma.MessageUncheckedCreateWithoutReplyToInput> | Prisma.MessageCreateWithoutReplyToInput[] | Prisma.MessageUncheckedCreateWithoutReplyToInput[]
  connectOrCreate?: Prisma.MessageCreateOrConnectWithoutReplyToInput | Prisma.MessageCreateOrConnectWithoutReplyToInput[]
  createMany?: Prisma.MessageCreateManyReplyToInputEnvelope
  connect?: Prisma.MessageWhereUniqueInput | Prisma.MessageWhereUniqueInput[]
}

export type MessageUncheckedCreateNestedManyWithoutReplyToInput = {
  create?: Prisma.XOR<Prisma.MessageCreateWithoutReplyToInput, Prisma.MessageUncheckedCreateWithoutReplyToInput> | Prisma.MessageCreateWithoutReplyToInput[] | Prisma.MessageUncheckedCreateWithoutReplyToInput[]
  connectOrCreate?: Prisma.MessageCreateOrConnectWithoutReplyToInput | Prisma.MessageCreateOrConnectWithoutReplyToInput[]
  createMany?: Prisma.MessageCreateManyReplyToInputEnvelope
  connect?: Prisma.MessageWhereUniqueInput | Prisma.MessageWhereUniqueInput[]
}

export type EnumMessageTypeFieldUpdateOperationsInput = {
  set?: $Enums.MessageType
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type MessageUpdateOneWithoutRepliesNestedInput = {
  create?: Prisma.XOR<Prisma.MessageCreateWithoutRepliesInput, Prisma.MessageUncheckedCreateWithoutRepliesInput>
  connectOrCreate?: Prisma.MessageCreateOrConnectWithoutRepliesInput
  upsert?: Prisma.MessageUpsertWithoutRepliesInput
  disconnect?: Prisma.MessageWhereInput | boolean
  delete?: Prisma.MessageWhereInput | boolean
  connect?: Prisma.MessageWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.MessageUpdateToOneWithWhereWithoutRepliesInput, Prisma.MessageUpdateWithoutRepliesInput>, Prisma.MessageUncheckedUpdateWithoutRepliesInput>
}

export type MessageUpdateManyWithoutReplyToNestedInput = {
  create?: Prisma.XOR<Prisma.MessageCreateWithoutReplyToInput, Prisma.MessageUncheckedCreateWithoutReplyToInput> | Prisma.MessageCreateWithoutReplyToInput[] | Prisma.MessageUncheckedCreateWithoutReplyToInput[]
  connectOrCreate?: Prisma.MessageCreateOrConnectWithoutReplyToInput | Prisma.MessageCreateOrConnectWithoutReplyToInput[]
  upsert?: Prisma.MessageUpsertWithWhereUniqueWithoutReplyToInput | Prisma.MessageUpsertWithWhereUniqueWithoutReplyToInput[]
  createMany?: Prisma.MessageCreateManyReplyToInputEnvelope
  set?: Prisma.MessageWhereUniqueInput | Prisma.MessageWhereUniqueInput[]
  disconnect?: Prisma.MessageWhereUniqueInput | Prisma.MessageWhereUniqueInput[]
  delete?: Prisma.MessageWhereUniqueInput | Prisma.MessageWhereUniqueInput[]
  connect?: Prisma.MessageWhereUniqueInput | Prisma.MessageWhereUniqueInput[]
  update?: Prisma.MessageUpdateWithWhereUniqueWithoutReplyToInput | Prisma.MessageUpdateWithWhereUniqueWithoutReplyToInput[]
  updateMany?: Prisma.MessageUpdateManyWithWhereWithoutReplyToInput | Prisma.MessageUpdateManyWithWhereWithoutReplyToInput[]
  deleteMany?: Prisma.MessageScalarWhereInput | Prisma.MessageScalarWhereInput[]
}

export type MessageUncheckedUpdateManyWithoutReplyToNestedInput = {
  create?: Prisma.XOR<Prisma.MessageCreateWithoutReplyToInput, Prisma.MessageUncheckedCreateWithoutReplyToInput> | Prisma.MessageCreateWithoutReplyToInput[] | Prisma.MessageUncheckedCreateWithoutReplyToInput[]
  connectOrCreate?: Prisma.MessageCreateOrConnectWithoutReplyToInput | Prisma.MessageCreateOrConnectWithoutReplyToInput[]
  upsert?: Prisma.MessageUpsertWithWhereUniqueWithoutReplyToInput | Prisma.MessageUpsertWithWhereUniqueWithoutReplyToInput[]
  createMany?: Prisma.MessageCreateManyReplyToInputEnvelope
  set?: Prisma.MessageWhereUniqueInput | Prisma.MessageWhereUniqueInput[]
  disconnect?: Prisma.MessageWhereUniqueInput | Prisma.MessageWhereUniqueInput[]
  delete?: Prisma.MessageWhereUniqueInput | Prisma.MessageWhereUniqueInput[]
  connect?: Prisma.MessageWhereUniqueInput | Prisma.MessageWhereUniqueInput[]
  update?: Prisma.MessageUpdateWithWhereUniqueWithoutReplyToInput | Prisma.MessageUpdateWithWhereUniqueWithoutReplyToInput[]
  updateMany?: Prisma.MessageUpdateManyWithWhereWithoutReplyToInput | Prisma.MessageUpdateManyWithWhereWithoutReplyToInput[]
  deleteMany?: Prisma.MessageScalarWhereInput | Prisma.MessageScalarWhereInput[]
}

export type MessageCreateNestedOneWithoutAttachmentsInput = {
  create?: Prisma.XOR<Prisma.MessageCreateWithoutAttachmentsInput, Prisma.MessageUncheckedCreateWithoutAttachmentsInput>
  connectOrCreate?: Prisma.MessageCreateOrConnectWithoutAttachmentsInput
  connect?: Prisma.MessageWhereUniqueInput
}

export type MessageUpdateOneRequiredWithoutAttachmentsNestedInput = {
  create?: Prisma.XOR<Prisma.MessageCreateWithoutAttachmentsInput, Prisma.MessageUncheckedCreateWithoutAttachmentsInput>
  connectOrCreate?: Prisma.MessageCreateOrConnectWithoutAttachmentsInput
  upsert?: Prisma.MessageUpsertWithoutAttachmentsInput
  connect?: Prisma.MessageWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.MessageUpdateToOneWithWhereWithoutAttachmentsInput, Prisma.MessageUpdateWithoutAttachmentsInput>, Prisma.MessageUncheckedUpdateWithoutAttachmentsInput>
}

export type MessageCreateWithoutAuthorInput = {
  id?: string
  content: string
  type?: $Enums.MessageType
  edited?: boolean
  editedAt?: Date | string | null
  deletedAt?: Date | string | null
  createdAt?: Date | string
  channel: Prisma.ChannelCreateNestedOneWithoutMessagesInput
  replyTo?: Prisma.MessageCreateNestedOneWithoutRepliesInput
  replies?: Prisma.MessageCreateNestedManyWithoutReplyToInput
  attachments?: Prisma.AttachmentCreateNestedManyWithoutMessageInput
}

export type MessageUncheckedCreateWithoutAuthorInput = {
  id?: string
  channelId: string
  content: string
  type?: $Enums.MessageType
  replyToId?: string | null
  edited?: boolean
  editedAt?: Date | string | null
  deletedAt?: Date | string | null
  createdAt?: Date | string
  replies?: Prisma.MessageUncheckedCreateNestedManyWithoutReplyToInput
  attachments?: Prisma.AttachmentUncheckedCreateNestedManyWithoutMessageInput
}

export type MessageCreateOrConnectWithoutAuthorInput = {
  where: Prisma.MessageWhereUniqueInput
  create: Prisma.XOR<Prisma.MessageCreateWithoutAuthorInput, Prisma.MessageUncheckedCreateWithoutAuthorInput>
}

export type MessageCreateManyAuthorInputEnvelope = {
  data: Prisma.MessageCreateManyAuthorInput | Prisma.MessageCreateManyAuthorInput[]
  skipDuplicates?: boolean
}

export type MessageUpsertWithWhereUniqueWithoutAuthorInput = {
  where: Prisma.MessageWhereUniqueInput
  update: Prisma.XOR<Prisma.MessageUpdateWithoutAuthorInput, Prisma.MessageUncheckedUpdateWithoutAuthorInput>
  create: Prisma.XOR<Prisma.MessageCreateWithoutAuthorInput, Prisma.MessageUncheckedCreateWithoutAuthorInput>
}

export type MessageUpdateWithWhereUniqueWithoutAuthorInput = {
  where: Prisma.MessageWhereUniqueInput
  data: Prisma.XOR<Prisma.MessageUpdateWithoutAuthorInput, Prisma.MessageUncheckedUpdateWithoutAuthorInput>
}

export type MessageUpdateManyWithWhereWithoutAuthorInput = {
  where: Prisma.MessageScalarWhereInput
  data: Prisma.XOR<Prisma.MessageUpdateManyMutationInput, Prisma.MessageUncheckedUpdateManyWithoutAuthorInput>
}

export type MessageScalarWhereInput = {
  AND?: Prisma.MessageScalarWhereInput | Prisma.MessageScalarWhereInput[]
  OR?: Prisma.MessageScalarWhereInput[]
  NOT?: Prisma.MessageScalarWhereInput | Prisma.MessageScalarWhereInput[]
  id?: Prisma.StringFilter<"Message"> | string
  channelId?: Prisma.StringFilter<"Message"> | string
  authorId?: Prisma.StringFilter<"Message"> | string
  content?: Prisma.StringFilter<"Message"> | string
  type?: Prisma.EnumMessageTypeFilter<"Message"> | $Enums.MessageType
  replyToId?: Prisma.StringNullableFilter<"Message"> | string | null
  edited?: Prisma.BoolFilter<"Message"> | boolean
  editedAt?: Prisma.DateTimeNullableFilter<"Message"> | Date | string | null
  deletedAt?: Prisma.DateTimeNullableFilter<"Message"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"Message"> | Date | string
}

export type MessageCreateWithoutChannelInput = {
  id?: string
  content: string
  type?: $Enums.MessageType
  edited?: boolean
  editedAt?: Date | string | null
  deletedAt?: Date | string | null
  createdAt?: Date | string
  author: Prisma.UserCreateNestedOneWithoutMessagesInput
  replyTo?: Prisma.MessageCreateNestedOneWithoutRepliesInput
  replies?: Prisma.MessageCreateNestedManyWithoutReplyToInput
  attachments?: Prisma.AttachmentCreateNestedManyWithoutMessageInput
}

export type MessageUncheckedCreateWithoutChannelInput = {
  id?: string
  authorId: string
  content: string
  type?: $Enums.MessageType
  replyToId?: string | null
  edited?: boolean
  editedAt?: Date | string | null
  deletedAt?: Date | string | null
  createdAt?: Date | string
  replies?: Prisma.MessageUncheckedCreateNestedManyWithoutReplyToInput
  attachments?: Prisma.AttachmentUncheckedCreateNestedManyWithoutMessageInput
}

export type MessageCreateOrConnectWithoutChannelInput = {
  where: Prisma.MessageWhereUniqueInput
  create: Prisma.XOR<Prisma.MessageCreateWithoutChannelInput, Prisma.MessageUncheckedCreateWithoutChannelInput>
}

export type MessageCreateManyChannelInputEnvelope = {
  data: Prisma.MessageCreateManyChannelInput | Prisma.MessageCreateManyChannelInput[]
  skipDuplicates?: boolean
}

export type MessageUpsertWithWhereUniqueWithoutChannelInput = {
  where: Prisma.MessageWhereUniqueInput
  update: Prisma.XOR<Prisma.MessageUpdateWithoutChannelInput, Prisma.MessageUncheckedUpdateWithoutChannelInput>
  create: Prisma.XOR<Prisma.MessageCreateWithoutChannelInput, Prisma.MessageUncheckedCreateWithoutChannelInput>
}

export type MessageUpdateWithWhereUniqueWithoutChannelInput = {
  where: Prisma.MessageWhereUniqueInput
  data: Prisma.XOR<Prisma.MessageUpdateWithoutChannelInput, Prisma.MessageUncheckedUpdateWithoutChannelInput>
}

export type MessageUpdateManyWithWhereWithoutChannelInput = {
  where: Prisma.MessageScalarWhereInput
  data: Prisma.XOR<Prisma.MessageUpdateManyMutationInput, Prisma.MessageUncheckedUpdateManyWithoutChannelInput>
}

export type MessageCreateWithoutRepliesInput = {
  id?: string
  content: string
  type?: $Enums.MessageType
  edited?: boolean
  editedAt?: Date | string | null
  deletedAt?: Date | string | null
  createdAt?: Date | string
  channel: Prisma.ChannelCreateNestedOneWithoutMessagesInput
  author: Prisma.UserCreateNestedOneWithoutMessagesInput
  replyTo?: Prisma.MessageCreateNestedOneWithoutRepliesInput
  attachments?: Prisma.AttachmentCreateNestedManyWithoutMessageInput
}

export type MessageUncheckedCreateWithoutRepliesInput = {
  id?: string
  channelId: string
  authorId: string
  content: string
  type?: $Enums.MessageType
  replyToId?: string | null
  edited?: boolean
  editedAt?: Date | string | null
  deletedAt?: Date | string | null
  createdAt?: Date | string
  attachments?: Prisma.AttachmentUncheckedCreateNestedManyWithoutMessageInput
}

export type MessageCreateOrConnectWithoutRepliesInput = {
  where: Prisma.MessageWhereUniqueInput
  create: Prisma.XOR<Prisma.MessageCreateWithoutRepliesInput, Prisma.MessageUncheckedCreateWithoutRepliesInput>
}

export type MessageCreateWithoutReplyToInput = {
  id?: string
  content: string
  type?: $Enums.MessageType
  edited?: boolean
  editedAt?: Date | string | null
  deletedAt?: Date | string | null
  createdAt?: Date | string
  channel: Prisma.ChannelCreateNestedOneWithoutMessagesInput
  author: Prisma.UserCreateNestedOneWithoutMessagesInput
  replies?: Prisma.MessageCreateNestedManyWithoutReplyToInput
  attachments?: Prisma.AttachmentCreateNestedManyWithoutMessageInput
}

export type MessageUncheckedCreateWithoutReplyToInput = {
  id?: string
  channelId: string
  authorId: string
  content: string
  type?: $Enums.MessageType
  edited?: boolean
  editedAt?: Date | string | null
  deletedAt?: Date | string | null
  createdAt?: Date | string
  replies?: Prisma.MessageUncheckedCreateNestedManyWithoutReplyToInput
  attachments?: Prisma.AttachmentUncheckedCreateNestedManyWithoutMessageInput
}

export type MessageCreateOrConnectWithoutReplyToInput = {
  where: Prisma.MessageWhereUniqueInput
  create: Prisma.XOR<Prisma.MessageCreateWithoutReplyToInput, Prisma.MessageUncheckedCreateWithoutReplyToInput>
}

export type MessageCreateManyReplyToInputEnvelope = {
  data: Prisma.MessageCreateManyReplyToInput | Prisma.MessageCreateManyReplyToInput[]
  skipDuplicates?: boolean
}

export type MessageUpsertWithoutRepliesInput = {
  update: Prisma.XOR<Prisma.MessageUpdateWithoutRepliesInput, Prisma.MessageUncheckedUpdateWithoutRepliesInput>
  create: Prisma.XOR<Prisma.MessageCreateWithoutRepliesInput, Prisma.MessageUncheckedCreateWithoutRepliesInput>
  where?: Prisma.MessageWhereInput
}

export type MessageUpdateToOneWithWhereWithoutRepliesInput = {
  where?: Prisma.MessageWhereInput
  data: Prisma.XOR<Prisma.MessageUpdateWithoutRepliesInput, Prisma.MessageUncheckedUpdateWithoutRepliesInput>
}

export type MessageUpdateWithoutRepliesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumMessageTypeFieldUpdateOperationsInput | $Enums.MessageType
  edited?: Prisma.BoolFieldUpdateOperationsInput | boolean
  editedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  channel?: Prisma.ChannelUpdateOneRequiredWithoutMessagesNestedInput
  author?: Prisma.UserUpdateOneRequiredWithoutMessagesNestedInput
  replyTo?: Prisma.MessageUpdateOneWithoutRepliesNestedInput
  attachments?: Prisma.AttachmentUpdateManyWithoutMessageNestedInput
}

export type MessageUncheckedUpdateWithoutRepliesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumMessageTypeFieldUpdateOperationsInput | $Enums.MessageType
  replyToId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  edited?: Prisma.BoolFieldUpdateOperationsInput | boolean
  editedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  attachments?: Prisma.AttachmentUncheckedUpdateManyWithoutMessageNestedInput
}

export type MessageUpsertWithWhereUniqueWithoutReplyToInput = {
  where: Prisma.MessageWhereUniqueInput
  update: Prisma.XOR<Prisma.MessageUpdateWithoutReplyToInput, Prisma.MessageUncheckedUpdateWithoutReplyToInput>
  create: Prisma.XOR<Prisma.MessageCreateWithoutReplyToInput, Prisma.MessageUncheckedCreateWithoutReplyToInput>
}

export type MessageUpdateWithWhereUniqueWithoutReplyToInput = {
  where: Prisma.MessageWhereUniqueInput
  data: Prisma.XOR<Prisma.MessageUpdateWithoutReplyToInput, Prisma.MessageUncheckedUpdateWithoutReplyToInput>
}

export type MessageUpdateManyWithWhereWithoutReplyToInput = {
  where: Prisma.MessageScalarWhereInput
  data: Prisma.XOR<Prisma.MessageUpdateManyMutationInput, Prisma.MessageUncheckedUpdateManyWithoutReplyToInput>
}

export type MessageCreateWithoutAttachmentsInput = {
  id?: string
  content: string
  type?: $Enums.MessageType
  edited?: boolean
  editedAt?: Date | string | null
  deletedAt?: Date | string | null
  createdAt?: Date | string
  channel: Prisma.ChannelCreateNestedOneWithoutMessagesInput
  author: Prisma.UserCreateNestedOneWithoutMessagesInput
  replyTo?: Prisma.MessageCreateNestedOneWithoutRepliesInput
  replies?: Prisma.MessageCreateNestedManyWithoutReplyToInput
}

export type MessageUncheckedCreateWithoutAttachmentsInput = {
  id?: string
  channelId: string
  authorId: string
  content: string
  type?: $Enums.MessageType
  replyToId?: string | null
  edited?: boolean
  editedAt?: Date | string | null
  deletedAt?: Date | string | null
  createdAt?: Date | string
  replies?: Prisma.MessageUncheckedCreateNestedManyWithoutReplyToInput
}

export type MessageCreateOrConnectWithoutAttachmentsInput = {
  where: Prisma.MessageWhereUniqueInput
  create: Prisma.XOR<Prisma.MessageCreateWithoutAttachmentsInput, Prisma.MessageUncheckedCreateWithoutAttachmentsInput>
}

export type MessageUpsertWithoutAttachmentsInput = {
  update: Prisma.XOR<Prisma.MessageUpdateWithoutAttachmentsInput, Prisma.MessageUncheckedUpdateWithoutAttachmentsInput>
  create: Prisma.XOR<Prisma.MessageCreateWithoutAttachmentsInput, Prisma.MessageUncheckedCreateWithoutAttachmentsInput>
  where?: Prisma.MessageWhereInput
}

export type MessageUpdateToOneWithWhereWithoutAttachmentsInput = {
  where?: Prisma.MessageWhereInput
  data: Prisma.XOR<Prisma.MessageUpdateWithoutAttachmentsInput, Prisma.MessageUncheckedUpdateWithoutAttachmentsInput>
}

export type MessageUpdateWithoutAttachmentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumMessageTypeFieldUpdateOperationsInput | $Enums.MessageType
  edited?: Prisma.BoolFieldUpdateOperationsInput | boolean
  editedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  channel?: Prisma.ChannelUpdateOneRequiredWithoutMessagesNestedInput
  author?: Prisma.UserUpdateOneRequiredWithoutMessagesNestedInput
  replyTo?: Prisma.MessageUpdateOneWithoutRepliesNestedInput
  replies?: Prisma.MessageUpdateManyWithoutReplyToNestedInput
}

export type MessageUncheckedUpdateWithoutAttachmentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumMessageTypeFieldUpdateOperationsInput | $Enums.MessageType
  replyToId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  edited?: Prisma.BoolFieldUpdateOperationsInput | boolean
  editedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  replies?: Prisma.MessageUncheckedUpdateManyWithoutReplyToNestedInput
}

export type MessageCreateManyAuthorInput = {
  id?: string
  channelId: string
  content: string
  type?: $Enums.MessageType
  replyToId?: string | null
  edited?: boolean
  editedAt?: Date | string | null
  deletedAt?: Date | string | null
  createdAt?: Date | string
}

export type MessageUpdateWithoutAuthorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumMessageTypeFieldUpdateOperationsInput | $Enums.MessageType
  edited?: Prisma.BoolFieldUpdateOperationsInput | boolean
  editedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  channel?: Prisma.ChannelUpdateOneRequiredWithoutMessagesNestedInput
  replyTo?: Prisma.MessageUpdateOneWithoutRepliesNestedInput
  replies?: Prisma.MessageUpdateManyWithoutReplyToNestedInput
  attachments?: Prisma.AttachmentUpdateManyWithoutMessageNestedInput
}

export type MessageUncheckedUpdateWithoutAuthorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumMessageTypeFieldUpdateOperationsInput | $Enums.MessageType
  replyToId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  edited?: Prisma.BoolFieldUpdateOperationsInput | boolean
  editedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  replies?: Prisma.MessageUncheckedUpdateManyWithoutReplyToNestedInput
  attachments?: Prisma.AttachmentUncheckedUpdateManyWithoutMessageNestedInput
}

export type MessageUncheckedUpdateManyWithoutAuthorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumMessageTypeFieldUpdateOperationsInput | $Enums.MessageType
  replyToId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  edited?: Prisma.BoolFieldUpdateOperationsInput | boolean
  editedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MessageCreateManyChannelInput = {
  id?: string
  authorId: string
  content: string
  type?: $Enums.MessageType
  replyToId?: string | null
  edited?: boolean
  editedAt?: Date | string | null
  deletedAt?: Date | string | null
  createdAt?: Date | string
}

export type MessageUpdateWithoutChannelInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumMessageTypeFieldUpdateOperationsInput | $Enums.MessageType
  edited?: Prisma.BoolFieldUpdateOperationsInput | boolean
  editedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  author?: Prisma.UserUpdateOneRequiredWithoutMessagesNestedInput
  replyTo?: Prisma.MessageUpdateOneWithoutRepliesNestedInput
  replies?: Prisma.MessageUpdateManyWithoutReplyToNestedInput
  attachments?: Prisma.AttachmentUpdateManyWithoutMessageNestedInput
}

export type MessageUncheckedUpdateWithoutChannelInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumMessageTypeFieldUpdateOperationsInput | $Enums.MessageType
  replyToId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  edited?: Prisma.BoolFieldUpdateOperationsInput | boolean
  editedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  replies?: Prisma.MessageUncheckedUpdateManyWithoutReplyToNestedInput
  attachments?: Prisma.AttachmentUncheckedUpdateManyWithoutMessageNestedInput
}

export type MessageUncheckedUpdateManyWithoutChannelInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumMessageTypeFieldUpdateOperationsInput | $Enums.MessageType
  replyToId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  edited?: Prisma.BoolFieldUpdateOperationsInput | boolean
  editedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MessageCreateManyReplyToInput = {
  id?: string
  channelId: string
  authorId: string
  content: string
  type?: $Enums.MessageType
  edited?: boolean
  editedAt?: Date | string | null
  deletedAt?: Date | string | null
  createdAt?: Date | string
}

export type MessageUpdateWithoutReplyToInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumMessageTypeFieldUpdateOperationsInput | $Enums.MessageType
  edited?: Prisma.BoolFieldUpdateOperationsInput | boolean
  editedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  channel?: Prisma.ChannelUpdateOneRequiredWithoutMessagesNestedInput
  author?: Prisma.UserUpdateOneRequiredWithoutMessagesNestedInput
  replies?: Prisma.MessageUpdateManyWithoutReplyToNestedInput
  attachments?: Prisma.AttachmentUpdateManyWithoutMessageNestedInput
}

export type MessageUncheckedUpdateWithoutReplyToInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumMessageTypeFieldUpdateOperationsInput | $Enums.MessageType
  edited?: Prisma.BoolFieldUpdateOperationsInput | boolean
  editedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  replies?: Prisma.MessageUncheckedUpdateManyWithoutReplyToNestedInput
  attachments?: Prisma.AttachmentUncheckedUpdateManyWithoutMessageNestedInput
}

export type MessageUncheckedUpdateManyWithoutReplyToInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumMessageTypeFieldUpdateOperationsInput | $Enums.MessageType
  edited?: Prisma.BoolFieldUpdateOperationsInput | boolean
  editedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type MessageCountOutputType
 */

export type MessageCountOutputType = {
  replies: number
  attachments: number
}

export type MessageCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  replies?: boolean | MessageCountOutputTypeCountRepliesArgs
  attachments?: boolean | MessageCountOutputTypeCountAttachmentsArgs
}

/**
 * MessageCountOutputType without action
 */
export type MessageCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MessageCountOutputType
   */
  select?: Prisma.MessageCountOutputTypeSelect<ExtArgs> | null
}

/**
 * MessageCountOutputType without action
 */
export type MessageCountOutputTypeCountRepliesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MessageWhereInput
}

/**
 * MessageCountOutputType without action
 */
export type MessageCountOutputTypeCountAttachmentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AttachmentWhereInput
}


export type MessageSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  channelId?: boolean
  authorId?: boolean
  content?: boolean
  type?: boolean
  replyToId?: boolean
  edited?: boolean
  editedAt?: boolean
  deletedAt?: boolean
  createdAt?: boolean
  channel?: boolean | Prisma.ChannelDefaultArgs<ExtArgs>
  author?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  replyTo?: boolean | Prisma.Message$replyToArgs<ExtArgs>
  replies?: boolean | Prisma.Message$repliesArgs<ExtArgs>
  attachments?: boolean | Prisma.Message$attachmentsArgs<ExtArgs>
  _count?: boolean | Prisma.MessageCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["message"]>

export type MessageSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  channelId?: boolean
  authorId?: boolean
  content?: boolean
  type?: boolean
  replyToId?: boolean
  edited?: boolean
  editedAt?: boolean
  deletedAt?: boolean
  createdAt?: boolean
  channel?: boolean | Prisma.ChannelDefaultArgs<ExtArgs>
  author?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  replyTo?: boolean | Prisma.Message$replyToArgs<ExtArgs>
}, ExtArgs["result"]["message"]>

export type MessageSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  channelId?: boolean
  authorId?: boolean
  content?: boolean
  type?: boolean
  replyToId?: boolean
  edited?: boolean
  editedAt?: boolean
  deletedAt?: boolean
  createdAt?: boolean
  channel?: boolean | Prisma.ChannelDefaultArgs<ExtArgs>
  author?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  replyTo?: boolean | Prisma.Message$replyToArgs<ExtArgs>
}, ExtArgs["result"]["message"]>

export type MessageSelectScalar = {
  id?: boolean
  channelId?: boolean
  authorId?: boolean
  content?: boolean
  type?: boolean
  replyToId?: boolean
  edited?: boolean
  editedAt?: boolean
  deletedAt?: boolean
  createdAt?: boolean
}

export type MessageOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "channelId" | "authorId" | "content" | "type" | "replyToId" | "edited" | "editedAt" | "deletedAt" | "createdAt", ExtArgs["result"]["message"]>
export type MessageInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  channel?: boolean | Prisma.ChannelDefaultArgs<ExtArgs>
  author?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  replyTo?: boolean | Prisma.Message$replyToArgs<ExtArgs>
  replies?: boolean | Prisma.Message$repliesArgs<ExtArgs>
  attachments?: boolean | Prisma.Message$attachmentsArgs<ExtArgs>
  _count?: boolean | Prisma.MessageCountOutputTypeDefaultArgs<ExtArgs>
}
export type MessageIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  channel?: boolean | Prisma.ChannelDefaultArgs<ExtArgs>
  author?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  replyTo?: boolean | Prisma.Message$replyToArgs<ExtArgs>
}
export type MessageIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  channel?: boolean | Prisma.ChannelDefaultArgs<ExtArgs>
  author?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  replyTo?: boolean | Prisma.Message$replyToArgs<ExtArgs>
}

export type $MessagePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Message"
  objects: {
    channel: Prisma.$ChannelPayload<ExtArgs>
    author: Prisma.$UserPayload<ExtArgs>
    replyTo: Prisma.$MessagePayload<ExtArgs> | null
    replies: Prisma.$MessagePayload<ExtArgs>[]
    attachments: Prisma.$AttachmentPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    channelId: string
    authorId: string
    content: string
    type: $Enums.MessageType
    replyToId: string | null
    edited: boolean
    editedAt: Date | null
    deletedAt: Date | null
    createdAt: Date
  }, ExtArgs["result"]["message"]>
  composites: {}
}

export type MessageGetPayload<S extends boolean | null | undefined | MessageDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MessagePayload, S>

export type MessageCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MessageFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MessageCountAggregateInputType | true
  }

export interface MessageDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Message'], meta: { name: 'Message' } }
  /**
   * Find zero or one Message that matches the filter.
   * @param {MessageFindUniqueArgs} args - Arguments to find a Message
   * @example
   * // Get one Message
   * const message = await prisma.message.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MessageFindUniqueArgs>(args: Prisma.SelectSubset<T, MessageFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MessageClient<runtime.Types.Result.GetResult<Prisma.$MessagePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Message that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MessageFindUniqueOrThrowArgs} args - Arguments to find a Message
   * @example
   * // Get one Message
   * const message = await prisma.message.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MessageFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MessageFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MessageClient<runtime.Types.Result.GetResult<Prisma.$MessagePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Message that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MessageFindFirstArgs} args - Arguments to find a Message
   * @example
   * // Get one Message
   * const message = await prisma.message.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MessageFindFirstArgs>(args?: Prisma.SelectSubset<T, MessageFindFirstArgs<ExtArgs>>): Prisma.Prisma__MessageClient<runtime.Types.Result.GetResult<Prisma.$MessagePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Message that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MessageFindFirstOrThrowArgs} args - Arguments to find a Message
   * @example
   * // Get one Message
   * const message = await prisma.message.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MessageFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MessageFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MessageClient<runtime.Types.Result.GetResult<Prisma.$MessagePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Messages that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MessageFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Messages
   * const messages = await prisma.message.findMany()
   * 
   * // Get first 10 Messages
   * const messages = await prisma.message.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const messageWithIdOnly = await prisma.message.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MessageFindManyArgs>(args?: Prisma.SelectSubset<T, MessageFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MessagePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Message.
   * @param {MessageCreateArgs} args - Arguments to create a Message.
   * @example
   * // Create one Message
   * const Message = await prisma.message.create({
   *   data: {
   *     // ... data to create a Message
   *   }
   * })
   * 
   */
  create<T extends MessageCreateArgs>(args: Prisma.SelectSubset<T, MessageCreateArgs<ExtArgs>>): Prisma.Prisma__MessageClient<runtime.Types.Result.GetResult<Prisma.$MessagePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Messages.
   * @param {MessageCreateManyArgs} args - Arguments to create many Messages.
   * @example
   * // Create many Messages
   * const message = await prisma.message.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MessageCreateManyArgs>(args?: Prisma.SelectSubset<T, MessageCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Messages and returns the data saved in the database.
   * @param {MessageCreateManyAndReturnArgs} args - Arguments to create many Messages.
   * @example
   * // Create many Messages
   * const message = await prisma.message.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Messages and only return the `id`
   * const messageWithIdOnly = await prisma.message.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MessageCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MessageCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MessagePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Message.
   * @param {MessageDeleteArgs} args - Arguments to delete one Message.
   * @example
   * // Delete one Message
   * const Message = await prisma.message.delete({
   *   where: {
   *     // ... filter to delete one Message
   *   }
   * })
   * 
   */
  delete<T extends MessageDeleteArgs>(args: Prisma.SelectSubset<T, MessageDeleteArgs<ExtArgs>>): Prisma.Prisma__MessageClient<runtime.Types.Result.GetResult<Prisma.$MessagePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Message.
   * @param {MessageUpdateArgs} args - Arguments to update one Message.
   * @example
   * // Update one Message
   * const message = await prisma.message.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MessageUpdateArgs>(args: Prisma.SelectSubset<T, MessageUpdateArgs<ExtArgs>>): Prisma.Prisma__MessageClient<runtime.Types.Result.GetResult<Prisma.$MessagePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Messages.
   * @param {MessageDeleteManyArgs} args - Arguments to filter Messages to delete.
   * @example
   * // Delete a few Messages
   * const { count } = await prisma.message.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MessageDeleteManyArgs>(args?: Prisma.SelectSubset<T, MessageDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Messages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MessageUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Messages
   * const message = await prisma.message.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MessageUpdateManyArgs>(args: Prisma.SelectSubset<T, MessageUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Messages and returns the data updated in the database.
   * @param {MessageUpdateManyAndReturnArgs} args - Arguments to update many Messages.
   * @example
   * // Update many Messages
   * const message = await prisma.message.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Messages and only return the `id`
   * const messageWithIdOnly = await prisma.message.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MessageUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MessageUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MessagePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Message.
   * @param {MessageUpsertArgs} args - Arguments to update or create a Message.
   * @example
   * // Update or create a Message
   * const message = await prisma.message.upsert({
   *   create: {
   *     // ... data to create a Message
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Message we want to update
   *   }
   * })
   */
  upsert<T extends MessageUpsertArgs>(args: Prisma.SelectSubset<T, MessageUpsertArgs<ExtArgs>>): Prisma.Prisma__MessageClient<runtime.Types.Result.GetResult<Prisma.$MessagePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Messages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MessageCountArgs} args - Arguments to filter Messages to count.
   * @example
   * // Count the number of Messages
   * const count = await prisma.message.count({
   *   where: {
   *     // ... the filter for the Messages we want to count
   *   }
   * })
  **/
  count<T extends MessageCountArgs>(
    args?: Prisma.Subset<T, MessageCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MessageCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Message.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MessageAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MessageAggregateArgs>(args: Prisma.Subset<T, MessageAggregateArgs>): Prisma.PrismaPromise<GetMessageAggregateType<T>>

  /**
   * Group by Message.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MessageGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MessageGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MessageGroupByArgs['orderBy'] }
      : { orderBy?: MessageGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MessageGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMessageGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Message model
 */
readonly fields: MessageFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Message.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MessageClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  channel<T extends Prisma.ChannelDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ChannelDefaultArgs<ExtArgs>>): Prisma.Prisma__ChannelClient<runtime.Types.Result.GetResult<Prisma.$ChannelPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  author<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  replyTo<T extends Prisma.Message$replyToArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Message$replyToArgs<ExtArgs>>): Prisma.Prisma__MessageClient<runtime.Types.Result.GetResult<Prisma.$MessagePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  replies<T extends Prisma.Message$repliesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Message$repliesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MessagePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  attachments<T extends Prisma.Message$attachmentsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Message$attachmentsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AttachmentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Message model
 */
export interface MessageFieldRefs {
  readonly id: Prisma.FieldRef<"Message", 'String'>
  readonly channelId: Prisma.FieldRef<"Message", 'String'>
  readonly authorId: Prisma.FieldRef<"Message", 'String'>
  readonly content: Prisma.FieldRef<"Message", 'String'>
  readonly type: Prisma.FieldRef<"Message", 'MessageType'>
  readonly replyToId: Prisma.FieldRef<"Message", 'String'>
  readonly edited: Prisma.FieldRef<"Message", 'Boolean'>
  readonly editedAt: Prisma.FieldRef<"Message", 'DateTime'>
  readonly deletedAt: Prisma.FieldRef<"Message", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"Message", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Message findUnique
 */
export type MessageFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Message
   */
  select?: Prisma.MessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Message
   */
  omit?: Prisma.MessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessageInclude<ExtArgs> | null
  /**
   * Filter, which Message to fetch.
   */
  where: Prisma.MessageWhereUniqueInput
}

/**
 * Message findUniqueOrThrow
 */
export type MessageFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Message
   */
  select?: Prisma.MessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Message
   */
  omit?: Prisma.MessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessageInclude<ExtArgs> | null
  /**
   * Filter, which Message to fetch.
   */
  where: Prisma.MessageWhereUniqueInput
}

/**
 * Message findFirst
 */
export type MessageFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Message
   */
  select?: Prisma.MessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Message
   */
  omit?: Prisma.MessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessageInclude<ExtArgs> | null
  /**
   * Filter, which Message to fetch.
   */
  where?: Prisma.MessageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Messages to fetch.
   */
  orderBy?: Prisma.MessageOrderByWithRelationInput | Prisma.MessageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Messages.
   */
  cursor?: Prisma.MessageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Messages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Messages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Messages.
   */
  distinct?: Prisma.MessageScalarFieldEnum | Prisma.MessageScalarFieldEnum[]
}

/**
 * Message findFirstOrThrow
 */
export type MessageFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Message
   */
  select?: Prisma.MessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Message
   */
  omit?: Prisma.MessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessageInclude<ExtArgs> | null
  /**
   * Filter, which Message to fetch.
   */
  where?: Prisma.MessageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Messages to fetch.
   */
  orderBy?: Prisma.MessageOrderByWithRelationInput | Prisma.MessageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Messages.
   */
  cursor?: Prisma.MessageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Messages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Messages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Messages.
   */
  distinct?: Prisma.MessageScalarFieldEnum | Prisma.MessageScalarFieldEnum[]
}

/**
 * Message findMany
 */
export type MessageFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Message
   */
  select?: Prisma.MessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Message
   */
  omit?: Prisma.MessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessageInclude<ExtArgs> | null
  /**
   * Filter, which Messages to fetch.
   */
  where?: Prisma.MessageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Messages to fetch.
   */
  orderBy?: Prisma.MessageOrderByWithRelationInput | Prisma.MessageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Messages.
   */
  cursor?: Prisma.MessageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Messages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Messages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Messages.
   */
  distinct?: Prisma.MessageScalarFieldEnum | Prisma.MessageScalarFieldEnum[]
}

/**
 * Message create
 */
export type MessageCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Message
   */
  select?: Prisma.MessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Message
   */
  omit?: Prisma.MessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessageInclude<ExtArgs> | null
  /**
   * The data needed to create a Message.
   */
  data: Prisma.XOR<Prisma.MessageCreateInput, Prisma.MessageUncheckedCreateInput>
}

/**
 * Message createMany
 */
export type MessageCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Messages.
   */
  data: Prisma.MessageCreateManyInput | Prisma.MessageCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Message createManyAndReturn
 */
export type MessageCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Message
   */
  select?: Prisma.MessageSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Message
   */
  omit?: Prisma.MessageOmit<ExtArgs> | null
  /**
   * The data used to create many Messages.
   */
  data: Prisma.MessageCreateManyInput | Prisma.MessageCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessageIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Message update
 */
export type MessageUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Message
   */
  select?: Prisma.MessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Message
   */
  omit?: Prisma.MessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessageInclude<ExtArgs> | null
  /**
   * The data needed to update a Message.
   */
  data: Prisma.XOR<Prisma.MessageUpdateInput, Prisma.MessageUncheckedUpdateInput>
  /**
   * Choose, which Message to update.
   */
  where: Prisma.MessageWhereUniqueInput
}

/**
 * Message updateMany
 */
export type MessageUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Messages.
   */
  data: Prisma.XOR<Prisma.MessageUpdateManyMutationInput, Prisma.MessageUncheckedUpdateManyInput>
  /**
   * Filter which Messages to update
   */
  where?: Prisma.MessageWhereInput
  /**
   * Limit how many Messages to update.
   */
  limit?: number
}

/**
 * Message updateManyAndReturn
 */
export type MessageUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Message
   */
  select?: Prisma.MessageSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Message
   */
  omit?: Prisma.MessageOmit<ExtArgs> | null
  /**
   * The data used to update Messages.
   */
  data: Prisma.XOR<Prisma.MessageUpdateManyMutationInput, Prisma.MessageUncheckedUpdateManyInput>
  /**
   * Filter which Messages to update
   */
  where?: Prisma.MessageWhereInput
  /**
   * Limit how many Messages to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessageIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Message upsert
 */
export type MessageUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Message
   */
  select?: Prisma.MessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Message
   */
  omit?: Prisma.MessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessageInclude<ExtArgs> | null
  /**
   * The filter to search for the Message to update in case it exists.
   */
  where: Prisma.MessageWhereUniqueInput
  /**
   * In case the Message found by the `where` argument doesn't exist, create a new Message with this data.
   */
  create: Prisma.XOR<Prisma.MessageCreateInput, Prisma.MessageUncheckedCreateInput>
  /**
   * In case the Message was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MessageUpdateInput, Prisma.MessageUncheckedUpdateInput>
}

/**
 * Message delete
 */
export type MessageDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Message
   */
  select?: Prisma.MessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Message
   */
  omit?: Prisma.MessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessageInclude<ExtArgs> | null
  /**
   * Filter which Message to delete.
   */
  where: Prisma.MessageWhereUniqueInput
}

/**
 * Message deleteMany
 */
export type MessageDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Messages to delete
   */
  where?: Prisma.MessageWhereInput
  /**
   * Limit how many Messages to delete.
   */
  limit?: number
}

/**
 * Message.replyTo
 */
export type Message$replyToArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Message
   */
  select?: Prisma.MessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Message
   */
  omit?: Prisma.MessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessageInclude<ExtArgs> | null
  where?: Prisma.MessageWhereInput
}

/**
 * Message.replies
 */
export type Message$repliesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Message
   */
  select?: Prisma.MessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Message
   */
  omit?: Prisma.MessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessageInclude<ExtArgs> | null
  where?: Prisma.MessageWhereInput
  orderBy?: Prisma.MessageOrderByWithRelationInput | Prisma.MessageOrderByWithRelationInput[]
  cursor?: Prisma.MessageWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.MessageScalarFieldEnum | Prisma.MessageScalarFieldEnum[]
}

/**
 * Message.attachments
 */
export type Message$attachmentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Attachment
   */
  select?: Prisma.AttachmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Attachment
   */
  omit?: Prisma.AttachmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AttachmentInclude<ExtArgs> | null
  where?: Prisma.AttachmentWhereInput
  orderBy?: Prisma.AttachmentOrderByWithRelationInput | Prisma.AttachmentOrderByWithRelationInput[]
  cursor?: Prisma.AttachmentWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AttachmentScalarFieldEnum | Prisma.AttachmentScalarFieldEnum[]
}

/**
 * Message without action
 */
export type MessageDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Message
   */
  select?: Prisma.MessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Message
   */
  omit?: Prisma.MessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessageInclude<ExtArgs> | null
}
