
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PMChannel` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PMChannel
 * 
 */
export type PMChannelModel = runtime.Types.Result.DefaultSelection<Prisma.$PMChannelPayload>

export type AggregatePMChannel = {
  _count: PMChannelCountAggregateOutputType | null
  _min: PMChannelMinAggregateOutputType | null
  _max: PMChannelMaxAggregateOutputType | null
}

export type PMChannelMinAggregateOutputType = {
  id: string | null
  createdAt: Date | null
}

export type PMChannelMaxAggregateOutputType = {
  id: string | null
  createdAt: Date | null
}

export type PMChannelCountAggregateOutputType = {
  id: number
  createdAt: number
  _all: number
}


export type PMChannelMinAggregateInputType = {
  id?: true
  createdAt?: true
}

export type PMChannelMaxAggregateInputType = {
  id?: true
  createdAt?: true
}

export type PMChannelCountAggregateInputType = {
  id?: true
  createdAt?: true
  _all?: true
}

export type PMChannelAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PMChannel to aggregate.
   */
  where?: Prisma.PMChannelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PMChannels to fetch.
   */
  orderBy?: Prisma.PMChannelOrderByWithRelationInput | Prisma.PMChannelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PMChannelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PMChannels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PMChannels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PMChannels
  **/
  _count?: true | PMChannelCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PMChannelMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PMChannelMaxAggregateInputType
}

export type GetPMChannelAggregateType<T extends PMChannelAggregateArgs> = {
      [P in keyof T & keyof AggregatePMChannel]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePMChannel[P]>
    : Prisma.GetScalarType<T[P], AggregatePMChannel[P]>
}




export type PMChannelGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PMChannelWhereInput
  orderBy?: Prisma.PMChannelOrderByWithAggregationInput | Prisma.PMChannelOrderByWithAggregationInput[]
  by: Prisma.PMChannelScalarFieldEnum[] | Prisma.PMChannelScalarFieldEnum
  having?: Prisma.PMChannelScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PMChannelCountAggregateInputType | true
  _min?: PMChannelMinAggregateInputType
  _max?: PMChannelMaxAggregateInputType
}

export type PMChannelGroupByOutputType = {
  id: string
  createdAt: Date
  _count: PMChannelCountAggregateOutputType | null
  _min: PMChannelMinAggregateOutputType | null
  _max: PMChannelMaxAggregateOutputType | null
}

export type GetPMChannelGroupByPayload<T extends PMChannelGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PMChannelGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PMChannelGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PMChannelGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PMChannelGroupByOutputType[P]>
      }
    >
  >



export type PMChannelWhereInput = {
  AND?: Prisma.PMChannelWhereInput | Prisma.PMChannelWhereInput[]
  OR?: Prisma.PMChannelWhereInput[]
  NOT?: Prisma.PMChannelWhereInput | Prisma.PMChannelWhereInput[]
  id?: Prisma.StringFilter<"PMChannel"> | string
  createdAt?: Prisma.DateTimeFilter<"PMChannel"> | Date | string
  participants?: Prisma.UserListRelationFilter
  messages?: Prisma.PrivateMessageListRelationFilter
}

export type PMChannelOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  participants?: Prisma.UserOrderByRelationAggregateInput
  messages?: Prisma.PrivateMessageOrderByRelationAggregateInput
}

export type PMChannelWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.PMChannelWhereInput | Prisma.PMChannelWhereInput[]
  OR?: Prisma.PMChannelWhereInput[]
  NOT?: Prisma.PMChannelWhereInput | Prisma.PMChannelWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"PMChannel"> | Date | string
  participants?: Prisma.UserListRelationFilter
  messages?: Prisma.PrivateMessageListRelationFilter
}, "id">

export type PMChannelOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.PMChannelCountOrderByAggregateInput
  _max?: Prisma.PMChannelMaxOrderByAggregateInput
  _min?: Prisma.PMChannelMinOrderByAggregateInput
}

export type PMChannelScalarWhereWithAggregatesInput = {
  AND?: Prisma.PMChannelScalarWhereWithAggregatesInput | Prisma.PMChannelScalarWhereWithAggregatesInput[]
  OR?: Prisma.PMChannelScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PMChannelScalarWhereWithAggregatesInput | Prisma.PMChannelScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PMChannel"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"PMChannel"> | Date | string
}

export type PMChannelCreateInput = {
  id?: string
  createdAt?: Date | string
  participants?: Prisma.UserCreateNestedManyWithoutPmChannelsInput
  messages?: Prisma.PrivateMessageCreateNestedManyWithoutChannelInput
}

export type PMChannelUncheckedCreateInput = {
  id?: string
  createdAt?: Date | string
  participants?: Prisma.UserUncheckedCreateNestedManyWithoutPmChannelsInput
  messages?: Prisma.PrivateMessageUncheckedCreateNestedManyWithoutChannelInput
}

export type PMChannelUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  participants?: Prisma.UserUpdateManyWithoutPmChannelsNestedInput
  messages?: Prisma.PrivateMessageUpdateManyWithoutChannelNestedInput
}

export type PMChannelUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  participants?: Prisma.UserUncheckedUpdateManyWithoutPmChannelsNestedInput
  messages?: Prisma.PrivateMessageUncheckedUpdateManyWithoutChannelNestedInput
}

export type PMChannelCreateManyInput = {
  id?: string
  createdAt?: Date | string
}

export type PMChannelUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PMChannelUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PMChannelListRelationFilter = {
  every?: Prisma.PMChannelWhereInput
  some?: Prisma.PMChannelWhereInput
  none?: Prisma.PMChannelWhereInput
}

export type PMChannelOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PMChannelCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type PMChannelMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type PMChannelMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type PMChannelScalarRelationFilter = {
  is?: Prisma.PMChannelWhereInput
  isNot?: Prisma.PMChannelWhereInput
}

export type PMChannelCreateNestedManyWithoutParticipantsInput = {
  create?: Prisma.XOR<Prisma.PMChannelCreateWithoutParticipantsInput, Prisma.PMChannelUncheckedCreateWithoutParticipantsInput> | Prisma.PMChannelCreateWithoutParticipantsInput[] | Prisma.PMChannelUncheckedCreateWithoutParticipantsInput[]
  connectOrCreate?: Prisma.PMChannelCreateOrConnectWithoutParticipantsInput | Prisma.PMChannelCreateOrConnectWithoutParticipantsInput[]
  connect?: Prisma.PMChannelWhereUniqueInput | Prisma.PMChannelWhereUniqueInput[]
}

export type PMChannelUncheckedCreateNestedManyWithoutParticipantsInput = {
  create?: Prisma.XOR<Prisma.PMChannelCreateWithoutParticipantsInput, Prisma.PMChannelUncheckedCreateWithoutParticipantsInput> | Prisma.PMChannelCreateWithoutParticipantsInput[] | Prisma.PMChannelUncheckedCreateWithoutParticipantsInput[]
  connectOrCreate?: Prisma.PMChannelCreateOrConnectWithoutParticipantsInput | Prisma.PMChannelCreateOrConnectWithoutParticipantsInput[]
  connect?: Prisma.PMChannelWhereUniqueInput | Prisma.PMChannelWhereUniqueInput[]
}

export type PMChannelUpdateManyWithoutParticipantsNestedInput = {
  create?: Prisma.XOR<Prisma.PMChannelCreateWithoutParticipantsInput, Prisma.PMChannelUncheckedCreateWithoutParticipantsInput> | Prisma.PMChannelCreateWithoutParticipantsInput[] | Prisma.PMChannelUncheckedCreateWithoutParticipantsInput[]
  connectOrCreate?: Prisma.PMChannelCreateOrConnectWithoutParticipantsInput | Prisma.PMChannelCreateOrConnectWithoutParticipantsInput[]
  upsert?: Prisma.PMChannelUpsertWithWhereUniqueWithoutParticipantsInput | Prisma.PMChannelUpsertWithWhereUniqueWithoutParticipantsInput[]
  set?: Prisma.PMChannelWhereUniqueInput | Prisma.PMChannelWhereUniqueInput[]
  disconnect?: Prisma.PMChannelWhereUniqueInput | Prisma.PMChannelWhereUniqueInput[]
  delete?: Prisma.PMChannelWhereUniqueInput | Prisma.PMChannelWhereUniqueInput[]
  connect?: Prisma.PMChannelWhereUniqueInput | Prisma.PMChannelWhereUniqueInput[]
  update?: Prisma.PMChannelUpdateWithWhereUniqueWithoutParticipantsInput | Prisma.PMChannelUpdateWithWhereUniqueWithoutParticipantsInput[]
  updateMany?: Prisma.PMChannelUpdateManyWithWhereWithoutParticipantsInput | Prisma.PMChannelUpdateManyWithWhereWithoutParticipantsInput[]
  deleteMany?: Prisma.PMChannelScalarWhereInput | Prisma.PMChannelScalarWhereInput[]
}

export type PMChannelUncheckedUpdateManyWithoutParticipantsNestedInput = {
  create?: Prisma.XOR<Prisma.PMChannelCreateWithoutParticipantsInput, Prisma.PMChannelUncheckedCreateWithoutParticipantsInput> | Prisma.PMChannelCreateWithoutParticipantsInput[] | Prisma.PMChannelUncheckedCreateWithoutParticipantsInput[]
  connectOrCreate?: Prisma.PMChannelCreateOrConnectWithoutParticipantsInput | Prisma.PMChannelCreateOrConnectWithoutParticipantsInput[]
  upsert?: Prisma.PMChannelUpsertWithWhereUniqueWithoutParticipantsInput | Prisma.PMChannelUpsertWithWhereUniqueWithoutParticipantsInput[]
  set?: Prisma.PMChannelWhereUniqueInput | Prisma.PMChannelWhereUniqueInput[]
  disconnect?: Prisma.PMChannelWhereUniqueInput | Prisma.PMChannelWhereUniqueInput[]
  delete?: Prisma.PMChannelWhereUniqueInput | Prisma.PMChannelWhereUniqueInput[]
  connect?: Prisma.PMChannelWhereUniqueInput | Prisma.PMChannelWhereUniqueInput[]
  update?: Prisma.PMChannelUpdateWithWhereUniqueWithoutParticipantsInput | Prisma.PMChannelUpdateWithWhereUniqueWithoutParticipantsInput[]
  updateMany?: Prisma.PMChannelUpdateManyWithWhereWithoutParticipantsInput | Prisma.PMChannelUpdateManyWithWhereWithoutParticipantsInput[]
  deleteMany?: Prisma.PMChannelScalarWhereInput | Prisma.PMChannelScalarWhereInput[]
}

export type PMChannelCreateNestedOneWithoutMessagesInput = {
  create?: Prisma.XOR<Prisma.PMChannelCreateWithoutMessagesInput, Prisma.PMChannelUncheckedCreateWithoutMessagesInput>
  connectOrCreate?: Prisma.PMChannelCreateOrConnectWithoutMessagesInput
  connect?: Prisma.PMChannelWhereUniqueInput
}

export type PMChannelUpdateOneRequiredWithoutMessagesNestedInput = {
  create?: Prisma.XOR<Prisma.PMChannelCreateWithoutMessagesInput, Prisma.PMChannelUncheckedCreateWithoutMessagesInput>
  connectOrCreate?: Prisma.PMChannelCreateOrConnectWithoutMessagesInput
  upsert?: Prisma.PMChannelUpsertWithoutMessagesInput
  connect?: Prisma.PMChannelWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PMChannelUpdateToOneWithWhereWithoutMessagesInput, Prisma.PMChannelUpdateWithoutMessagesInput>, Prisma.PMChannelUncheckedUpdateWithoutMessagesInput>
}

export type PMChannelCreateWithoutParticipantsInput = {
  id?: string
  createdAt?: Date | string
  messages?: Prisma.PrivateMessageCreateNestedManyWithoutChannelInput
}

export type PMChannelUncheckedCreateWithoutParticipantsInput = {
  id?: string
  createdAt?: Date | string
  messages?: Prisma.PrivateMessageUncheckedCreateNestedManyWithoutChannelInput
}

export type PMChannelCreateOrConnectWithoutParticipantsInput = {
  where: Prisma.PMChannelWhereUniqueInput
  create: Prisma.XOR<Prisma.PMChannelCreateWithoutParticipantsInput, Prisma.PMChannelUncheckedCreateWithoutParticipantsInput>
}

export type PMChannelUpsertWithWhereUniqueWithoutParticipantsInput = {
  where: Prisma.PMChannelWhereUniqueInput
  update: Prisma.XOR<Prisma.PMChannelUpdateWithoutParticipantsInput, Prisma.PMChannelUncheckedUpdateWithoutParticipantsInput>
  create: Prisma.XOR<Prisma.PMChannelCreateWithoutParticipantsInput, Prisma.PMChannelUncheckedCreateWithoutParticipantsInput>
}

export type PMChannelUpdateWithWhereUniqueWithoutParticipantsInput = {
  where: Prisma.PMChannelWhereUniqueInput
  data: Prisma.XOR<Prisma.PMChannelUpdateWithoutParticipantsInput, Prisma.PMChannelUncheckedUpdateWithoutParticipantsInput>
}

export type PMChannelUpdateManyWithWhereWithoutParticipantsInput = {
  where: Prisma.PMChannelScalarWhereInput
  data: Prisma.XOR<Prisma.PMChannelUpdateManyMutationInput, Prisma.PMChannelUncheckedUpdateManyWithoutParticipantsInput>
}

export type PMChannelScalarWhereInput = {
  AND?: Prisma.PMChannelScalarWhereInput | Prisma.PMChannelScalarWhereInput[]
  OR?: Prisma.PMChannelScalarWhereInput[]
  NOT?: Prisma.PMChannelScalarWhereInput | Prisma.PMChannelScalarWhereInput[]
  id?: Prisma.StringFilter<"PMChannel"> | string
  createdAt?: Prisma.DateTimeFilter<"PMChannel"> | Date | string
}

export type PMChannelCreateWithoutMessagesInput = {
  id?: string
  createdAt?: Date | string
  participants?: Prisma.UserCreateNestedManyWithoutPmChannelsInput
}

export type PMChannelUncheckedCreateWithoutMessagesInput = {
  id?: string
  createdAt?: Date | string
  participants?: Prisma.UserUncheckedCreateNestedManyWithoutPmChannelsInput
}

export type PMChannelCreateOrConnectWithoutMessagesInput = {
  where: Prisma.PMChannelWhereUniqueInput
  create: Prisma.XOR<Prisma.PMChannelCreateWithoutMessagesInput, Prisma.PMChannelUncheckedCreateWithoutMessagesInput>
}

export type PMChannelUpsertWithoutMessagesInput = {
  update: Prisma.XOR<Prisma.PMChannelUpdateWithoutMessagesInput, Prisma.PMChannelUncheckedUpdateWithoutMessagesInput>
  create: Prisma.XOR<Prisma.PMChannelCreateWithoutMessagesInput, Prisma.PMChannelUncheckedCreateWithoutMessagesInput>
  where?: Prisma.PMChannelWhereInput
}

export type PMChannelUpdateToOneWithWhereWithoutMessagesInput = {
  where?: Prisma.PMChannelWhereInput
  data: Prisma.XOR<Prisma.PMChannelUpdateWithoutMessagesInput, Prisma.PMChannelUncheckedUpdateWithoutMessagesInput>
}

export type PMChannelUpdateWithoutMessagesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  participants?: Prisma.UserUpdateManyWithoutPmChannelsNestedInput
}

export type PMChannelUncheckedUpdateWithoutMessagesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  participants?: Prisma.UserUncheckedUpdateManyWithoutPmChannelsNestedInput
}

export type PMChannelUpdateWithoutParticipantsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  messages?: Prisma.PrivateMessageUpdateManyWithoutChannelNestedInput
}

export type PMChannelUncheckedUpdateWithoutParticipantsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  messages?: Prisma.PrivateMessageUncheckedUpdateManyWithoutChannelNestedInput
}

export type PMChannelUncheckedUpdateManyWithoutParticipantsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type PMChannelCountOutputType
 */

export type PMChannelCountOutputType = {
  participants: number
  messages: number
}

export type PMChannelCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  participants?: boolean | PMChannelCountOutputTypeCountParticipantsArgs
  messages?: boolean | PMChannelCountOutputTypeCountMessagesArgs
}

/**
 * PMChannelCountOutputType without action
 */
export type PMChannelCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PMChannelCountOutputType
   */
  select?: Prisma.PMChannelCountOutputTypeSelect<ExtArgs> | null
}

/**
 * PMChannelCountOutputType without action
 */
export type PMChannelCountOutputTypeCountParticipantsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserWhereInput
}

/**
 * PMChannelCountOutputType without action
 */
export type PMChannelCountOutputTypeCountMessagesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PrivateMessageWhereInput
}


export type PMChannelSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  participants?: boolean | Prisma.PMChannel$participantsArgs<ExtArgs>
  messages?: boolean | Prisma.PMChannel$messagesArgs<ExtArgs>
  _count?: boolean | Prisma.PMChannelCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["pMChannel"]>

export type PMChannelSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["pMChannel"]>

export type PMChannelSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["pMChannel"]>

export type PMChannelSelectScalar = {
  id?: boolean
  createdAt?: boolean
}

export type PMChannelOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt", ExtArgs["result"]["pMChannel"]>
export type PMChannelInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  participants?: boolean | Prisma.PMChannel$participantsArgs<ExtArgs>
  messages?: boolean | Prisma.PMChannel$messagesArgs<ExtArgs>
  _count?: boolean | Prisma.PMChannelCountOutputTypeDefaultArgs<ExtArgs>
}
export type PMChannelIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type PMChannelIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $PMChannelPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PMChannel"
  objects: {
    participants: Prisma.$UserPayload<ExtArgs>[]
    messages: Prisma.$PrivateMessagePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    createdAt: Date
  }, ExtArgs["result"]["pMChannel"]>
  composites: {}
}

export type PMChannelGetPayload<S extends boolean | null | undefined | PMChannelDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PMChannelPayload, S>

export type PMChannelCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PMChannelFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PMChannelCountAggregateInputType | true
  }

export interface PMChannelDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PMChannel'], meta: { name: 'PMChannel' } }
  /**
   * Find zero or one PMChannel that matches the filter.
   * @param {PMChannelFindUniqueArgs} args - Arguments to find a PMChannel
   * @example
   * // Get one PMChannel
   * const pMChannel = await prisma.pMChannel.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PMChannelFindUniqueArgs>(args: Prisma.SelectSubset<T, PMChannelFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PMChannelClient<runtime.Types.Result.GetResult<Prisma.$PMChannelPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PMChannel that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PMChannelFindUniqueOrThrowArgs} args - Arguments to find a PMChannel
   * @example
   * // Get one PMChannel
   * const pMChannel = await prisma.pMChannel.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PMChannelFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PMChannelFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PMChannelClient<runtime.Types.Result.GetResult<Prisma.$PMChannelPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PMChannel that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PMChannelFindFirstArgs} args - Arguments to find a PMChannel
   * @example
   * // Get one PMChannel
   * const pMChannel = await prisma.pMChannel.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PMChannelFindFirstArgs>(args?: Prisma.SelectSubset<T, PMChannelFindFirstArgs<ExtArgs>>): Prisma.Prisma__PMChannelClient<runtime.Types.Result.GetResult<Prisma.$PMChannelPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PMChannel that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PMChannelFindFirstOrThrowArgs} args - Arguments to find a PMChannel
   * @example
   * // Get one PMChannel
   * const pMChannel = await prisma.pMChannel.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PMChannelFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PMChannelFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PMChannelClient<runtime.Types.Result.GetResult<Prisma.$PMChannelPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PMChannels that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PMChannelFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PMChannels
   * const pMChannels = await prisma.pMChannel.findMany()
   * 
   * // Get first 10 PMChannels
   * const pMChannels = await prisma.pMChannel.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const pMChannelWithIdOnly = await prisma.pMChannel.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PMChannelFindManyArgs>(args?: Prisma.SelectSubset<T, PMChannelFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PMChannelPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PMChannel.
   * @param {PMChannelCreateArgs} args - Arguments to create a PMChannel.
   * @example
   * // Create one PMChannel
   * const PMChannel = await prisma.pMChannel.create({
   *   data: {
   *     // ... data to create a PMChannel
   *   }
   * })
   * 
   */
  create<T extends PMChannelCreateArgs>(args: Prisma.SelectSubset<T, PMChannelCreateArgs<ExtArgs>>): Prisma.Prisma__PMChannelClient<runtime.Types.Result.GetResult<Prisma.$PMChannelPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PMChannels.
   * @param {PMChannelCreateManyArgs} args - Arguments to create many PMChannels.
   * @example
   * // Create many PMChannels
   * const pMChannel = await prisma.pMChannel.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PMChannelCreateManyArgs>(args?: Prisma.SelectSubset<T, PMChannelCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PMChannels and returns the data saved in the database.
   * @param {PMChannelCreateManyAndReturnArgs} args - Arguments to create many PMChannels.
   * @example
   * // Create many PMChannels
   * const pMChannel = await prisma.pMChannel.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PMChannels and only return the `id`
   * const pMChannelWithIdOnly = await prisma.pMChannel.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PMChannelCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PMChannelCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PMChannelPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PMChannel.
   * @param {PMChannelDeleteArgs} args - Arguments to delete one PMChannel.
   * @example
   * // Delete one PMChannel
   * const PMChannel = await prisma.pMChannel.delete({
   *   where: {
   *     // ... filter to delete one PMChannel
   *   }
   * })
   * 
   */
  delete<T extends PMChannelDeleteArgs>(args: Prisma.SelectSubset<T, PMChannelDeleteArgs<ExtArgs>>): Prisma.Prisma__PMChannelClient<runtime.Types.Result.GetResult<Prisma.$PMChannelPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PMChannel.
   * @param {PMChannelUpdateArgs} args - Arguments to update one PMChannel.
   * @example
   * // Update one PMChannel
   * const pMChannel = await prisma.pMChannel.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PMChannelUpdateArgs>(args: Prisma.SelectSubset<T, PMChannelUpdateArgs<ExtArgs>>): Prisma.Prisma__PMChannelClient<runtime.Types.Result.GetResult<Prisma.$PMChannelPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PMChannels.
   * @param {PMChannelDeleteManyArgs} args - Arguments to filter PMChannels to delete.
   * @example
   * // Delete a few PMChannels
   * const { count } = await prisma.pMChannel.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PMChannelDeleteManyArgs>(args?: Prisma.SelectSubset<T, PMChannelDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PMChannels.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PMChannelUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PMChannels
   * const pMChannel = await prisma.pMChannel.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PMChannelUpdateManyArgs>(args: Prisma.SelectSubset<T, PMChannelUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PMChannels and returns the data updated in the database.
   * @param {PMChannelUpdateManyAndReturnArgs} args - Arguments to update many PMChannels.
   * @example
   * // Update many PMChannels
   * const pMChannel = await prisma.pMChannel.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PMChannels and only return the `id`
   * const pMChannelWithIdOnly = await prisma.pMChannel.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PMChannelUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PMChannelUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PMChannelPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PMChannel.
   * @param {PMChannelUpsertArgs} args - Arguments to update or create a PMChannel.
   * @example
   * // Update or create a PMChannel
   * const pMChannel = await prisma.pMChannel.upsert({
   *   create: {
   *     // ... data to create a PMChannel
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PMChannel we want to update
   *   }
   * })
   */
  upsert<T extends PMChannelUpsertArgs>(args: Prisma.SelectSubset<T, PMChannelUpsertArgs<ExtArgs>>): Prisma.Prisma__PMChannelClient<runtime.Types.Result.GetResult<Prisma.$PMChannelPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PMChannels.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PMChannelCountArgs} args - Arguments to filter PMChannels to count.
   * @example
   * // Count the number of PMChannels
   * const count = await prisma.pMChannel.count({
   *   where: {
   *     // ... the filter for the PMChannels we want to count
   *   }
   * })
  **/
  count<T extends PMChannelCountArgs>(
    args?: Prisma.Subset<T, PMChannelCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PMChannelCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PMChannel.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PMChannelAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PMChannelAggregateArgs>(args: Prisma.Subset<T, PMChannelAggregateArgs>): Prisma.PrismaPromise<GetPMChannelAggregateType<T>>

  /**
   * Group by PMChannel.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PMChannelGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PMChannelGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PMChannelGroupByArgs['orderBy'] }
      : { orderBy?: PMChannelGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PMChannelGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPMChannelGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PMChannel model
 */
readonly fields: PMChannelFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PMChannel.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PMChannelClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  participants<T extends Prisma.PMChannel$participantsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PMChannel$participantsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  messages<T extends Prisma.PMChannel$messagesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PMChannel$messagesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PrivateMessagePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PMChannel model
 */
export interface PMChannelFieldRefs {
  readonly id: Prisma.FieldRef<"PMChannel", 'String'>
  readonly createdAt: Prisma.FieldRef<"PMChannel", 'DateTime'>
}
    

// Custom InputTypes
/**
 * PMChannel findUnique
 */
export type PMChannelFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PMChannel
   */
  select?: Prisma.PMChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PMChannel
   */
  omit?: Prisma.PMChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PMChannelInclude<ExtArgs> | null
  /**
   * Filter, which PMChannel to fetch.
   */
  where: Prisma.PMChannelWhereUniqueInput
}

/**
 * PMChannel findUniqueOrThrow
 */
export type PMChannelFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PMChannel
   */
  select?: Prisma.PMChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PMChannel
   */
  omit?: Prisma.PMChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PMChannelInclude<ExtArgs> | null
  /**
   * Filter, which PMChannel to fetch.
   */
  where: Prisma.PMChannelWhereUniqueInput
}

/**
 * PMChannel findFirst
 */
export type PMChannelFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PMChannel
   */
  select?: Prisma.PMChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PMChannel
   */
  omit?: Prisma.PMChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PMChannelInclude<ExtArgs> | null
  /**
   * Filter, which PMChannel to fetch.
   */
  where?: Prisma.PMChannelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PMChannels to fetch.
   */
  orderBy?: Prisma.PMChannelOrderByWithRelationInput | Prisma.PMChannelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PMChannels.
   */
  cursor?: Prisma.PMChannelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PMChannels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PMChannels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PMChannels.
   */
  distinct?: Prisma.PMChannelScalarFieldEnum | Prisma.PMChannelScalarFieldEnum[]
}

/**
 * PMChannel findFirstOrThrow
 */
export type PMChannelFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PMChannel
   */
  select?: Prisma.PMChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PMChannel
   */
  omit?: Prisma.PMChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PMChannelInclude<ExtArgs> | null
  /**
   * Filter, which PMChannel to fetch.
   */
  where?: Prisma.PMChannelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PMChannels to fetch.
   */
  orderBy?: Prisma.PMChannelOrderByWithRelationInput | Prisma.PMChannelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PMChannels.
   */
  cursor?: Prisma.PMChannelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PMChannels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PMChannels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PMChannels.
   */
  distinct?: Prisma.PMChannelScalarFieldEnum | Prisma.PMChannelScalarFieldEnum[]
}

/**
 * PMChannel findMany
 */
export type PMChannelFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PMChannel
   */
  select?: Prisma.PMChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PMChannel
   */
  omit?: Prisma.PMChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PMChannelInclude<ExtArgs> | null
  /**
   * Filter, which PMChannels to fetch.
   */
  where?: Prisma.PMChannelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PMChannels to fetch.
   */
  orderBy?: Prisma.PMChannelOrderByWithRelationInput | Prisma.PMChannelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PMChannels.
   */
  cursor?: Prisma.PMChannelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PMChannels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PMChannels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PMChannels.
   */
  distinct?: Prisma.PMChannelScalarFieldEnum | Prisma.PMChannelScalarFieldEnum[]
}

/**
 * PMChannel create
 */
export type PMChannelCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PMChannel
   */
  select?: Prisma.PMChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PMChannel
   */
  omit?: Prisma.PMChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PMChannelInclude<ExtArgs> | null
  /**
   * The data needed to create a PMChannel.
   */
  data?: Prisma.XOR<Prisma.PMChannelCreateInput, Prisma.PMChannelUncheckedCreateInput>
}

/**
 * PMChannel createMany
 */
export type PMChannelCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PMChannels.
   */
  data: Prisma.PMChannelCreateManyInput | Prisma.PMChannelCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PMChannel createManyAndReturn
 */
export type PMChannelCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PMChannel
   */
  select?: Prisma.PMChannelSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PMChannel
   */
  omit?: Prisma.PMChannelOmit<ExtArgs> | null
  /**
   * The data used to create many PMChannels.
   */
  data: Prisma.PMChannelCreateManyInput | Prisma.PMChannelCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PMChannel update
 */
export type PMChannelUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PMChannel
   */
  select?: Prisma.PMChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PMChannel
   */
  omit?: Prisma.PMChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PMChannelInclude<ExtArgs> | null
  /**
   * The data needed to update a PMChannel.
   */
  data: Prisma.XOR<Prisma.PMChannelUpdateInput, Prisma.PMChannelUncheckedUpdateInput>
  /**
   * Choose, which PMChannel to update.
   */
  where: Prisma.PMChannelWhereUniqueInput
}

/**
 * PMChannel updateMany
 */
export type PMChannelUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PMChannels.
   */
  data: Prisma.XOR<Prisma.PMChannelUpdateManyMutationInput, Prisma.PMChannelUncheckedUpdateManyInput>
  /**
   * Filter which PMChannels to update
   */
  where?: Prisma.PMChannelWhereInput
  /**
   * Limit how many PMChannels to update.
   */
  limit?: number
}

/**
 * PMChannel updateManyAndReturn
 */
export type PMChannelUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PMChannel
   */
  select?: Prisma.PMChannelSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PMChannel
   */
  omit?: Prisma.PMChannelOmit<ExtArgs> | null
  /**
   * The data used to update PMChannels.
   */
  data: Prisma.XOR<Prisma.PMChannelUpdateManyMutationInput, Prisma.PMChannelUncheckedUpdateManyInput>
  /**
   * Filter which PMChannels to update
   */
  where?: Prisma.PMChannelWhereInput
  /**
   * Limit how many PMChannels to update.
   */
  limit?: number
}

/**
 * PMChannel upsert
 */
export type PMChannelUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PMChannel
   */
  select?: Prisma.PMChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PMChannel
   */
  omit?: Prisma.PMChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PMChannelInclude<ExtArgs> | null
  /**
   * The filter to search for the PMChannel to update in case it exists.
   */
  where: Prisma.PMChannelWhereUniqueInput
  /**
   * In case the PMChannel found by the `where` argument doesn't exist, create a new PMChannel with this data.
   */
  create: Prisma.XOR<Prisma.PMChannelCreateInput, Prisma.PMChannelUncheckedCreateInput>
  /**
   * In case the PMChannel was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PMChannelUpdateInput, Prisma.PMChannelUncheckedUpdateInput>
}

/**
 * PMChannel delete
 */
export type PMChannelDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PMChannel
   */
  select?: Prisma.PMChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PMChannel
   */
  omit?: Prisma.PMChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PMChannelInclude<ExtArgs> | null
  /**
   * Filter which PMChannel to delete.
   */
  where: Prisma.PMChannelWhereUniqueInput
}

/**
 * PMChannel deleteMany
 */
export type PMChannelDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PMChannels to delete
   */
  where?: Prisma.PMChannelWhereInput
  /**
   * Limit how many PMChannels to delete.
   */
  limit?: number
}

/**
 * PMChannel.participants
 */
export type PMChannel$participantsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  cursor?: Prisma.UserWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * PMChannel.messages
 */
export type PMChannel$messagesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrivateMessage
   */
  select?: Prisma.PrivateMessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PrivateMessage
   */
  omit?: Prisma.PrivateMessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PrivateMessageInclude<ExtArgs> | null
  where?: Prisma.PrivateMessageWhereInput
  orderBy?: Prisma.PrivateMessageOrderByWithRelationInput | Prisma.PrivateMessageOrderByWithRelationInput[]
  cursor?: Prisma.PrivateMessageWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PrivateMessageScalarFieldEnum | Prisma.PrivateMessageScalarFieldEnum[]
}

/**
 * PMChannel without action
 */
export type PMChannelDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PMChannel
   */
  select?: Prisma.PMChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PMChannel
   */
  omit?: Prisma.PMChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PMChannelInclude<ExtArgs> | null
}
