
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PrivateMessage` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PrivateMessage
 * 
 */
export type PrivateMessageModel = runtime.Types.Result.DefaultSelection<Prisma.$PrivateMessagePayload>

export type AggregatePrivateMessage = {
  _count: PrivateMessageCountAggregateOutputType | null
  _min: PrivateMessageMinAggregateOutputType | null
  _max: PrivateMessageMaxAggregateOutputType | null
}

export type PrivateMessageMinAggregateOutputType = {
  id: string | null
  channelId: string | null
  authorId: string | null
  content: string | null
  editedAt: Date | null
  deletedAt: Date | null
  createdAt: Date | null
}

export type PrivateMessageMaxAggregateOutputType = {
  id: string | null
  channelId: string | null
  authorId: string | null
  content: string | null
  editedAt: Date | null
  deletedAt: Date | null
  createdAt: Date | null
}

export type PrivateMessageCountAggregateOutputType = {
  id: number
  channelId: number
  authorId: number
  content: number
  editedAt: number
  deletedAt: number
  createdAt: number
  _all: number
}


export type PrivateMessageMinAggregateInputType = {
  id?: true
  channelId?: true
  authorId?: true
  content?: true
  editedAt?: true
  deletedAt?: true
  createdAt?: true
}

export type PrivateMessageMaxAggregateInputType = {
  id?: true
  channelId?: true
  authorId?: true
  content?: true
  editedAt?: true
  deletedAt?: true
  createdAt?: true
}

export type PrivateMessageCountAggregateInputType = {
  id?: true
  channelId?: true
  authorId?: true
  content?: true
  editedAt?: true
  deletedAt?: true
  createdAt?: true
  _all?: true
}

export type PrivateMessageAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PrivateMessage to aggregate.
   */
  where?: Prisma.PrivateMessageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PrivateMessages to fetch.
   */
  orderBy?: Prisma.PrivateMessageOrderByWithRelationInput | Prisma.PrivateMessageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PrivateMessageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PrivateMessages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PrivateMessages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PrivateMessages
  **/
  _count?: true | PrivateMessageCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PrivateMessageMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PrivateMessageMaxAggregateInputType
}

export type GetPrivateMessageAggregateType<T extends PrivateMessageAggregateArgs> = {
      [P in keyof T & keyof AggregatePrivateMessage]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePrivateMessage[P]>
    : Prisma.GetScalarType<T[P], AggregatePrivateMessage[P]>
}




export type PrivateMessageGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PrivateMessageWhereInput
  orderBy?: Prisma.PrivateMessageOrderByWithAggregationInput | Prisma.PrivateMessageOrderByWithAggregationInput[]
  by: Prisma.PrivateMessageScalarFieldEnum[] | Prisma.PrivateMessageScalarFieldEnum
  having?: Prisma.PrivateMessageScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PrivateMessageCountAggregateInputType | true
  _min?: PrivateMessageMinAggregateInputType
  _max?: PrivateMessageMaxAggregateInputType
}

export type PrivateMessageGroupByOutputType = {
  id: string
  channelId: string
  authorId: string
  content: string
  editedAt: Date | null
  deletedAt: Date | null
  createdAt: Date
  _count: PrivateMessageCountAggregateOutputType | null
  _min: PrivateMessageMinAggregateOutputType | null
  _max: PrivateMessageMaxAggregateOutputType | null
}

export type GetPrivateMessageGroupByPayload<T extends PrivateMessageGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PrivateMessageGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PrivateMessageGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PrivateMessageGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PrivateMessageGroupByOutputType[P]>
      }
    >
  >



export type PrivateMessageWhereInput = {
  AND?: Prisma.PrivateMessageWhereInput | Prisma.PrivateMessageWhereInput[]
  OR?: Prisma.PrivateMessageWhereInput[]
  NOT?: Prisma.PrivateMessageWhereInput | Prisma.PrivateMessageWhereInput[]
  id?: Prisma.StringFilter<"PrivateMessage"> | string
  channelId?: Prisma.StringFilter<"PrivateMessage"> | string
  authorId?: Prisma.StringFilter<"PrivateMessage"> | string
  content?: Prisma.StringFilter<"PrivateMessage"> | string
  editedAt?: Prisma.DateTimeNullableFilter<"PrivateMessage"> | Date | string | null
  deletedAt?: Prisma.DateTimeNullableFilter<"PrivateMessage"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"PrivateMessage"> | Date | string
  channel?: Prisma.XOR<Prisma.PMChannelScalarRelationFilter, Prisma.PMChannelWhereInput>
  author?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type PrivateMessageOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  content?: Prisma.SortOrder
  editedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  channel?: Prisma.PMChannelOrderByWithRelationInput
  author?: Prisma.UserOrderByWithRelationInput
}

export type PrivateMessageWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.PrivateMessageWhereInput | Prisma.PrivateMessageWhereInput[]
  OR?: Prisma.PrivateMessageWhereInput[]
  NOT?: Prisma.PrivateMessageWhereInput | Prisma.PrivateMessageWhereInput[]
  channelId?: Prisma.StringFilter<"PrivateMessage"> | string
  authorId?: Prisma.StringFilter<"PrivateMessage"> | string
  content?: Prisma.StringFilter<"PrivateMessage"> | string
  editedAt?: Prisma.DateTimeNullableFilter<"PrivateMessage"> | Date | string | null
  deletedAt?: Prisma.DateTimeNullableFilter<"PrivateMessage"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"PrivateMessage"> | Date | string
  channel?: Prisma.XOR<Prisma.PMChannelScalarRelationFilter, Prisma.PMChannelWhereInput>
  author?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type PrivateMessageOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  content?: Prisma.SortOrder
  editedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.PrivateMessageCountOrderByAggregateInput
  _max?: Prisma.PrivateMessageMaxOrderByAggregateInput
  _min?: Prisma.PrivateMessageMinOrderByAggregateInput
}

export type PrivateMessageScalarWhereWithAggregatesInput = {
  AND?: Prisma.PrivateMessageScalarWhereWithAggregatesInput | Prisma.PrivateMessageScalarWhereWithAggregatesInput[]
  OR?: Prisma.PrivateMessageScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PrivateMessageScalarWhereWithAggregatesInput | Prisma.PrivateMessageScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PrivateMessage"> | string
  channelId?: Prisma.StringWithAggregatesFilter<"PrivateMessage"> | string
  authorId?: Prisma.StringWithAggregatesFilter<"PrivateMessage"> | string
  content?: Prisma.StringWithAggregatesFilter<"PrivateMessage"> | string
  editedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"PrivateMessage"> | Date | string | null
  deletedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"PrivateMessage"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"PrivateMessage"> | Date | string
}

export type PrivateMessageCreateInput = {
  id?: string
  content: string
  editedAt?: Date | string | null
  deletedAt?: Date | string | null
  createdAt?: Date | string
  channel: Prisma.PMChannelCreateNestedOneWithoutMessagesInput
  author: Prisma.UserCreateNestedOneWithoutPrivateMessagesInput
}

export type PrivateMessageUncheckedCreateInput = {
  id?: string
  channelId: string
  authorId: string
  content: string
  editedAt?: Date | string | null
  deletedAt?: Date | string | null
  createdAt?: Date | string
}

export type PrivateMessageUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  editedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  channel?: Prisma.PMChannelUpdateOneRequiredWithoutMessagesNestedInput
  author?: Prisma.UserUpdateOneRequiredWithoutPrivateMessagesNestedInput
}

export type PrivateMessageUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  editedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PrivateMessageCreateManyInput = {
  id?: string
  channelId: string
  authorId: string
  content: string
  editedAt?: Date | string | null
  deletedAt?: Date | string | null
  createdAt?: Date | string
}

export type PrivateMessageUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  editedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PrivateMessageUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  editedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PrivateMessageListRelationFilter = {
  every?: Prisma.PrivateMessageWhereInput
  some?: Prisma.PrivateMessageWhereInput
  none?: Prisma.PrivateMessageWhereInput
}

export type PrivateMessageOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PrivateMessageCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  content?: Prisma.SortOrder
  editedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type PrivateMessageMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  content?: Prisma.SortOrder
  editedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type PrivateMessageMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  content?: Prisma.SortOrder
  editedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type PrivateMessageCreateNestedManyWithoutAuthorInput = {
  create?: Prisma.XOR<Prisma.PrivateMessageCreateWithoutAuthorInput, Prisma.PrivateMessageUncheckedCreateWithoutAuthorInput> | Prisma.PrivateMessageCreateWithoutAuthorInput[] | Prisma.PrivateMessageUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?: Prisma.PrivateMessageCreateOrConnectWithoutAuthorInput | Prisma.PrivateMessageCreateOrConnectWithoutAuthorInput[]
  createMany?: Prisma.PrivateMessageCreateManyAuthorInputEnvelope
  connect?: Prisma.PrivateMessageWhereUniqueInput | Prisma.PrivateMessageWhereUniqueInput[]
}

export type PrivateMessageUncheckedCreateNestedManyWithoutAuthorInput = {
  create?: Prisma.XOR<Prisma.PrivateMessageCreateWithoutAuthorInput, Prisma.PrivateMessageUncheckedCreateWithoutAuthorInput> | Prisma.PrivateMessageCreateWithoutAuthorInput[] | Prisma.PrivateMessageUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?: Prisma.PrivateMessageCreateOrConnectWithoutAuthorInput | Prisma.PrivateMessageCreateOrConnectWithoutAuthorInput[]
  createMany?: Prisma.PrivateMessageCreateManyAuthorInputEnvelope
  connect?: Prisma.PrivateMessageWhereUniqueInput | Prisma.PrivateMessageWhereUniqueInput[]
}

export type PrivateMessageUpdateManyWithoutAuthorNestedInput = {
  create?: Prisma.XOR<Prisma.PrivateMessageCreateWithoutAuthorInput, Prisma.PrivateMessageUncheckedCreateWithoutAuthorInput> | Prisma.PrivateMessageCreateWithoutAuthorInput[] | Prisma.PrivateMessageUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?: Prisma.PrivateMessageCreateOrConnectWithoutAuthorInput | Prisma.PrivateMessageCreateOrConnectWithoutAuthorInput[]
  upsert?: Prisma.PrivateMessageUpsertWithWhereUniqueWithoutAuthorInput | Prisma.PrivateMessageUpsertWithWhereUniqueWithoutAuthorInput[]
  createMany?: Prisma.PrivateMessageCreateManyAuthorInputEnvelope
  set?: Prisma.PrivateMessageWhereUniqueInput | Prisma.PrivateMessageWhereUniqueInput[]
  disconnect?: Prisma.PrivateMessageWhereUniqueInput | Prisma.PrivateMessageWhereUniqueInput[]
  delete?: Prisma.PrivateMessageWhereUniqueInput | Prisma.PrivateMessageWhereUniqueInput[]
  connect?: Prisma.PrivateMessageWhereUniqueInput | Prisma.PrivateMessageWhereUniqueInput[]
  update?: Prisma.PrivateMessageUpdateWithWhereUniqueWithoutAuthorInput | Prisma.PrivateMessageUpdateWithWhereUniqueWithoutAuthorInput[]
  updateMany?: Prisma.PrivateMessageUpdateManyWithWhereWithoutAuthorInput | Prisma.PrivateMessageUpdateManyWithWhereWithoutAuthorInput[]
  deleteMany?: Prisma.PrivateMessageScalarWhereInput | Prisma.PrivateMessageScalarWhereInput[]
}

export type PrivateMessageUncheckedUpdateManyWithoutAuthorNestedInput = {
  create?: Prisma.XOR<Prisma.PrivateMessageCreateWithoutAuthorInput, Prisma.PrivateMessageUncheckedCreateWithoutAuthorInput> | Prisma.PrivateMessageCreateWithoutAuthorInput[] | Prisma.PrivateMessageUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?: Prisma.PrivateMessageCreateOrConnectWithoutAuthorInput | Prisma.PrivateMessageCreateOrConnectWithoutAuthorInput[]
  upsert?: Prisma.PrivateMessageUpsertWithWhereUniqueWithoutAuthorInput | Prisma.PrivateMessageUpsertWithWhereUniqueWithoutAuthorInput[]
  createMany?: Prisma.PrivateMessageCreateManyAuthorInputEnvelope
  set?: Prisma.PrivateMessageWhereUniqueInput | Prisma.PrivateMessageWhereUniqueInput[]
  disconnect?: Prisma.PrivateMessageWhereUniqueInput | Prisma.PrivateMessageWhereUniqueInput[]
  delete?: Prisma.PrivateMessageWhereUniqueInput | Prisma.PrivateMessageWhereUniqueInput[]
  connect?: Prisma.PrivateMessageWhereUniqueInput | Prisma.PrivateMessageWhereUniqueInput[]
  update?: Prisma.PrivateMessageUpdateWithWhereUniqueWithoutAuthorInput | Prisma.PrivateMessageUpdateWithWhereUniqueWithoutAuthorInput[]
  updateMany?: Prisma.PrivateMessageUpdateManyWithWhereWithoutAuthorInput | Prisma.PrivateMessageUpdateManyWithWhereWithoutAuthorInput[]
  deleteMany?: Prisma.PrivateMessageScalarWhereInput | Prisma.PrivateMessageScalarWhereInput[]
}

export type PrivateMessageCreateNestedManyWithoutChannelInput = {
  create?: Prisma.XOR<Prisma.PrivateMessageCreateWithoutChannelInput, Prisma.PrivateMessageUncheckedCreateWithoutChannelInput> | Prisma.PrivateMessageCreateWithoutChannelInput[] | Prisma.PrivateMessageUncheckedCreateWithoutChannelInput[]
  connectOrCreate?: Prisma.PrivateMessageCreateOrConnectWithoutChannelInput | Prisma.PrivateMessageCreateOrConnectWithoutChannelInput[]
  createMany?: Prisma.PrivateMessageCreateManyChannelInputEnvelope
  connect?: Prisma.PrivateMessageWhereUniqueInput | Prisma.PrivateMessageWhereUniqueInput[]
}

export type PrivateMessageUncheckedCreateNestedManyWithoutChannelInput = {
  create?: Prisma.XOR<Prisma.PrivateMessageCreateWithoutChannelInput, Prisma.PrivateMessageUncheckedCreateWithoutChannelInput> | Prisma.PrivateMessageCreateWithoutChannelInput[] | Prisma.PrivateMessageUncheckedCreateWithoutChannelInput[]
  connectOrCreate?: Prisma.PrivateMessageCreateOrConnectWithoutChannelInput | Prisma.PrivateMessageCreateOrConnectWithoutChannelInput[]
  createMany?: Prisma.PrivateMessageCreateManyChannelInputEnvelope
  connect?: Prisma.PrivateMessageWhereUniqueInput | Prisma.PrivateMessageWhereUniqueInput[]
}

export type PrivateMessageUpdateManyWithoutChannelNestedInput = {
  create?: Prisma.XOR<Prisma.PrivateMessageCreateWithoutChannelInput, Prisma.PrivateMessageUncheckedCreateWithoutChannelInput> | Prisma.PrivateMessageCreateWithoutChannelInput[] | Prisma.PrivateMessageUncheckedCreateWithoutChannelInput[]
  connectOrCreate?: Prisma.PrivateMessageCreateOrConnectWithoutChannelInput | Prisma.PrivateMessageCreateOrConnectWithoutChannelInput[]
  upsert?: Prisma.PrivateMessageUpsertWithWhereUniqueWithoutChannelInput | Prisma.PrivateMessageUpsertWithWhereUniqueWithoutChannelInput[]
  createMany?: Prisma.PrivateMessageCreateManyChannelInputEnvelope
  set?: Prisma.PrivateMessageWhereUniqueInput | Prisma.PrivateMessageWhereUniqueInput[]
  disconnect?: Prisma.PrivateMessageWhereUniqueInput | Prisma.PrivateMessageWhereUniqueInput[]
  delete?: Prisma.PrivateMessageWhereUniqueInput | Prisma.PrivateMessageWhereUniqueInput[]
  connect?: Prisma.PrivateMessageWhereUniqueInput | Prisma.PrivateMessageWhereUniqueInput[]
  update?: Prisma.PrivateMessageUpdateWithWhereUniqueWithoutChannelInput | Prisma.PrivateMessageUpdateWithWhereUniqueWithoutChannelInput[]
  updateMany?: Prisma.PrivateMessageUpdateManyWithWhereWithoutChannelInput | Prisma.PrivateMessageUpdateManyWithWhereWithoutChannelInput[]
  deleteMany?: Prisma.PrivateMessageScalarWhereInput | Prisma.PrivateMessageScalarWhereInput[]
}

export type PrivateMessageUncheckedUpdateManyWithoutChannelNestedInput = {
  create?: Prisma.XOR<Prisma.PrivateMessageCreateWithoutChannelInput, Prisma.PrivateMessageUncheckedCreateWithoutChannelInput> | Prisma.PrivateMessageCreateWithoutChannelInput[] | Prisma.PrivateMessageUncheckedCreateWithoutChannelInput[]
  connectOrCreate?: Prisma.PrivateMessageCreateOrConnectWithoutChannelInput | Prisma.PrivateMessageCreateOrConnectWithoutChannelInput[]
  upsert?: Prisma.PrivateMessageUpsertWithWhereUniqueWithoutChannelInput | Prisma.PrivateMessageUpsertWithWhereUniqueWithoutChannelInput[]
  createMany?: Prisma.PrivateMessageCreateManyChannelInputEnvelope
  set?: Prisma.PrivateMessageWhereUniqueInput | Prisma.PrivateMessageWhereUniqueInput[]
  disconnect?: Prisma.PrivateMessageWhereUniqueInput | Prisma.PrivateMessageWhereUniqueInput[]
  delete?: Prisma.PrivateMessageWhereUniqueInput | Prisma.PrivateMessageWhereUniqueInput[]
  connect?: Prisma.PrivateMessageWhereUniqueInput | Prisma.PrivateMessageWhereUniqueInput[]
  update?: Prisma.PrivateMessageUpdateWithWhereUniqueWithoutChannelInput | Prisma.PrivateMessageUpdateWithWhereUniqueWithoutChannelInput[]
  updateMany?: Prisma.PrivateMessageUpdateManyWithWhereWithoutChannelInput | Prisma.PrivateMessageUpdateManyWithWhereWithoutChannelInput[]
  deleteMany?: Prisma.PrivateMessageScalarWhereInput | Prisma.PrivateMessageScalarWhereInput[]
}

export type PrivateMessageCreateWithoutAuthorInput = {
  id?: string
  content: string
  editedAt?: Date | string | null
  deletedAt?: Date | string | null
  createdAt?: Date | string
  channel: Prisma.PMChannelCreateNestedOneWithoutMessagesInput
}

export type PrivateMessageUncheckedCreateWithoutAuthorInput = {
  id?: string
  channelId: string
  content: string
  editedAt?: Date | string | null
  deletedAt?: Date | string | null
  createdAt?: Date | string
}

export type PrivateMessageCreateOrConnectWithoutAuthorInput = {
  where: Prisma.PrivateMessageWhereUniqueInput
  create: Prisma.XOR<Prisma.PrivateMessageCreateWithoutAuthorInput, Prisma.PrivateMessageUncheckedCreateWithoutAuthorInput>
}

export type PrivateMessageCreateManyAuthorInputEnvelope = {
  data: Prisma.PrivateMessageCreateManyAuthorInput | Prisma.PrivateMessageCreateManyAuthorInput[]
  skipDuplicates?: boolean
}

export type PrivateMessageUpsertWithWhereUniqueWithoutAuthorInput = {
  where: Prisma.PrivateMessageWhereUniqueInput
  update: Prisma.XOR<Prisma.PrivateMessageUpdateWithoutAuthorInput, Prisma.PrivateMessageUncheckedUpdateWithoutAuthorInput>
  create: Prisma.XOR<Prisma.PrivateMessageCreateWithoutAuthorInput, Prisma.PrivateMessageUncheckedCreateWithoutAuthorInput>
}

export type PrivateMessageUpdateWithWhereUniqueWithoutAuthorInput = {
  where: Prisma.PrivateMessageWhereUniqueInput
  data: Prisma.XOR<Prisma.PrivateMessageUpdateWithoutAuthorInput, Prisma.PrivateMessageUncheckedUpdateWithoutAuthorInput>
}

export type PrivateMessageUpdateManyWithWhereWithoutAuthorInput = {
  where: Prisma.PrivateMessageScalarWhereInput
  data: Prisma.XOR<Prisma.PrivateMessageUpdateManyMutationInput, Prisma.PrivateMessageUncheckedUpdateManyWithoutAuthorInput>
}

export type PrivateMessageScalarWhereInput = {
  AND?: Prisma.PrivateMessageScalarWhereInput | Prisma.PrivateMessageScalarWhereInput[]
  OR?: Prisma.PrivateMessageScalarWhereInput[]
  NOT?: Prisma.PrivateMessageScalarWhereInput | Prisma.PrivateMessageScalarWhereInput[]
  id?: Prisma.StringFilter<"PrivateMessage"> | string
  channelId?: Prisma.StringFilter<"PrivateMessage"> | string
  authorId?: Prisma.StringFilter<"PrivateMessage"> | string
  content?: Prisma.StringFilter<"PrivateMessage"> | string
  editedAt?: Prisma.DateTimeNullableFilter<"PrivateMessage"> | Date | string | null
  deletedAt?: Prisma.DateTimeNullableFilter<"PrivateMessage"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"PrivateMessage"> | Date | string
}

export type PrivateMessageCreateWithoutChannelInput = {
  id?: string
  content: string
  editedAt?: Date | string | null
  deletedAt?: Date | string | null
  createdAt?: Date | string
  author: Prisma.UserCreateNestedOneWithoutPrivateMessagesInput
}

export type PrivateMessageUncheckedCreateWithoutChannelInput = {
  id?: string
  authorId: string
  content: string
  editedAt?: Date | string | null
  deletedAt?: Date | string | null
  createdAt?: Date | string
}

export type PrivateMessageCreateOrConnectWithoutChannelInput = {
  where: Prisma.PrivateMessageWhereUniqueInput
  create: Prisma.XOR<Prisma.PrivateMessageCreateWithoutChannelInput, Prisma.PrivateMessageUncheckedCreateWithoutChannelInput>
}

export type PrivateMessageCreateManyChannelInputEnvelope = {
  data: Prisma.PrivateMessageCreateManyChannelInput | Prisma.PrivateMessageCreateManyChannelInput[]
  skipDuplicates?: boolean
}

export type PrivateMessageUpsertWithWhereUniqueWithoutChannelInput = {
  where: Prisma.PrivateMessageWhereUniqueInput
  update: Prisma.XOR<Prisma.PrivateMessageUpdateWithoutChannelInput, Prisma.PrivateMessageUncheckedUpdateWithoutChannelInput>
  create: Prisma.XOR<Prisma.PrivateMessageCreateWithoutChannelInput, Prisma.PrivateMessageUncheckedCreateWithoutChannelInput>
}

export type PrivateMessageUpdateWithWhereUniqueWithoutChannelInput = {
  where: Prisma.PrivateMessageWhereUniqueInput
  data: Prisma.XOR<Prisma.PrivateMessageUpdateWithoutChannelInput, Prisma.PrivateMessageUncheckedUpdateWithoutChannelInput>
}

export type PrivateMessageUpdateManyWithWhereWithoutChannelInput = {
  where: Prisma.PrivateMessageScalarWhereInput
  data: Prisma.XOR<Prisma.PrivateMessageUpdateManyMutationInput, Prisma.PrivateMessageUncheckedUpdateManyWithoutChannelInput>
}

export type PrivateMessageCreateManyAuthorInput = {
  id?: string
  channelId: string
  content: string
  editedAt?: Date | string | null
  deletedAt?: Date | string | null
  createdAt?: Date | string
}

export type PrivateMessageUpdateWithoutAuthorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  editedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  channel?: Prisma.PMChannelUpdateOneRequiredWithoutMessagesNestedInput
}

export type PrivateMessageUncheckedUpdateWithoutAuthorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  editedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PrivateMessageUncheckedUpdateManyWithoutAuthorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  editedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PrivateMessageCreateManyChannelInput = {
  id?: string
  authorId: string
  content: string
  editedAt?: Date | string | null
  deletedAt?: Date | string | null
  createdAt?: Date | string
}

export type PrivateMessageUpdateWithoutChannelInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  editedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  author?: Prisma.UserUpdateOneRequiredWithoutPrivateMessagesNestedInput
}

export type PrivateMessageUncheckedUpdateWithoutChannelInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  editedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PrivateMessageUncheckedUpdateManyWithoutChannelInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  editedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type PrivateMessageSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  channelId?: boolean
  authorId?: boolean
  content?: boolean
  editedAt?: boolean
  deletedAt?: boolean
  createdAt?: boolean
  channel?: boolean | Prisma.PMChannelDefaultArgs<ExtArgs>
  author?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["privateMessage"]>

export type PrivateMessageSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  channelId?: boolean
  authorId?: boolean
  content?: boolean
  editedAt?: boolean
  deletedAt?: boolean
  createdAt?: boolean
  channel?: boolean | Prisma.PMChannelDefaultArgs<ExtArgs>
  author?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["privateMessage"]>

export type PrivateMessageSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  channelId?: boolean
  authorId?: boolean
  content?: boolean
  editedAt?: boolean
  deletedAt?: boolean
  createdAt?: boolean
  channel?: boolean | Prisma.PMChannelDefaultArgs<ExtArgs>
  author?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["privateMessage"]>

export type PrivateMessageSelectScalar = {
  id?: boolean
  channelId?: boolean
  authorId?: boolean
  content?: boolean
  editedAt?: boolean
  deletedAt?: boolean
  createdAt?: boolean
}

export type PrivateMessageOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "channelId" | "authorId" | "content" | "editedAt" | "deletedAt" | "createdAt", ExtArgs["result"]["privateMessage"]>
export type PrivateMessageInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  channel?: boolean | Prisma.PMChannelDefaultArgs<ExtArgs>
  author?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type PrivateMessageIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  channel?: boolean | Prisma.PMChannelDefaultArgs<ExtArgs>
  author?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type PrivateMessageIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  channel?: boolean | Prisma.PMChannelDefaultArgs<ExtArgs>
  author?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $PrivateMessagePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PrivateMessage"
  objects: {
    channel: Prisma.$PMChannelPayload<ExtArgs>
    author: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    channelId: string
    authorId: string
    content: string
    editedAt: Date | null
    deletedAt: Date | null
    createdAt: Date
  }, ExtArgs["result"]["privateMessage"]>
  composites: {}
}

export type PrivateMessageGetPayload<S extends boolean | null | undefined | PrivateMessageDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PrivateMessagePayload, S>

export type PrivateMessageCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PrivateMessageFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PrivateMessageCountAggregateInputType | true
  }

export interface PrivateMessageDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PrivateMessage'], meta: { name: 'PrivateMessage' } }
  /**
   * Find zero or one PrivateMessage that matches the filter.
   * @param {PrivateMessageFindUniqueArgs} args - Arguments to find a PrivateMessage
   * @example
   * // Get one PrivateMessage
   * const privateMessage = await prisma.privateMessage.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PrivateMessageFindUniqueArgs>(args: Prisma.SelectSubset<T, PrivateMessageFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PrivateMessageClient<runtime.Types.Result.GetResult<Prisma.$PrivateMessagePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PrivateMessage that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PrivateMessageFindUniqueOrThrowArgs} args - Arguments to find a PrivateMessage
   * @example
   * // Get one PrivateMessage
   * const privateMessage = await prisma.privateMessage.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PrivateMessageFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PrivateMessageFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PrivateMessageClient<runtime.Types.Result.GetResult<Prisma.$PrivateMessagePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PrivateMessage that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PrivateMessageFindFirstArgs} args - Arguments to find a PrivateMessage
   * @example
   * // Get one PrivateMessage
   * const privateMessage = await prisma.privateMessage.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PrivateMessageFindFirstArgs>(args?: Prisma.SelectSubset<T, PrivateMessageFindFirstArgs<ExtArgs>>): Prisma.Prisma__PrivateMessageClient<runtime.Types.Result.GetResult<Prisma.$PrivateMessagePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PrivateMessage that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PrivateMessageFindFirstOrThrowArgs} args - Arguments to find a PrivateMessage
   * @example
   * // Get one PrivateMessage
   * const privateMessage = await prisma.privateMessage.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PrivateMessageFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PrivateMessageFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PrivateMessageClient<runtime.Types.Result.GetResult<Prisma.$PrivateMessagePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PrivateMessages that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PrivateMessageFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PrivateMessages
   * const privateMessages = await prisma.privateMessage.findMany()
   * 
   * // Get first 10 PrivateMessages
   * const privateMessages = await prisma.privateMessage.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const privateMessageWithIdOnly = await prisma.privateMessage.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PrivateMessageFindManyArgs>(args?: Prisma.SelectSubset<T, PrivateMessageFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PrivateMessagePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PrivateMessage.
   * @param {PrivateMessageCreateArgs} args - Arguments to create a PrivateMessage.
   * @example
   * // Create one PrivateMessage
   * const PrivateMessage = await prisma.privateMessage.create({
   *   data: {
   *     // ... data to create a PrivateMessage
   *   }
   * })
   * 
   */
  create<T extends PrivateMessageCreateArgs>(args: Prisma.SelectSubset<T, PrivateMessageCreateArgs<ExtArgs>>): Prisma.Prisma__PrivateMessageClient<runtime.Types.Result.GetResult<Prisma.$PrivateMessagePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PrivateMessages.
   * @param {PrivateMessageCreateManyArgs} args - Arguments to create many PrivateMessages.
   * @example
   * // Create many PrivateMessages
   * const privateMessage = await prisma.privateMessage.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PrivateMessageCreateManyArgs>(args?: Prisma.SelectSubset<T, PrivateMessageCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PrivateMessages and returns the data saved in the database.
   * @param {PrivateMessageCreateManyAndReturnArgs} args - Arguments to create many PrivateMessages.
   * @example
   * // Create many PrivateMessages
   * const privateMessage = await prisma.privateMessage.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PrivateMessages and only return the `id`
   * const privateMessageWithIdOnly = await prisma.privateMessage.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PrivateMessageCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PrivateMessageCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PrivateMessagePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PrivateMessage.
   * @param {PrivateMessageDeleteArgs} args - Arguments to delete one PrivateMessage.
   * @example
   * // Delete one PrivateMessage
   * const PrivateMessage = await prisma.privateMessage.delete({
   *   where: {
   *     // ... filter to delete one PrivateMessage
   *   }
   * })
   * 
   */
  delete<T extends PrivateMessageDeleteArgs>(args: Prisma.SelectSubset<T, PrivateMessageDeleteArgs<ExtArgs>>): Prisma.Prisma__PrivateMessageClient<runtime.Types.Result.GetResult<Prisma.$PrivateMessagePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PrivateMessage.
   * @param {PrivateMessageUpdateArgs} args - Arguments to update one PrivateMessage.
   * @example
   * // Update one PrivateMessage
   * const privateMessage = await prisma.privateMessage.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PrivateMessageUpdateArgs>(args: Prisma.SelectSubset<T, PrivateMessageUpdateArgs<ExtArgs>>): Prisma.Prisma__PrivateMessageClient<runtime.Types.Result.GetResult<Prisma.$PrivateMessagePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PrivateMessages.
   * @param {PrivateMessageDeleteManyArgs} args - Arguments to filter PrivateMessages to delete.
   * @example
   * // Delete a few PrivateMessages
   * const { count } = await prisma.privateMessage.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PrivateMessageDeleteManyArgs>(args?: Prisma.SelectSubset<T, PrivateMessageDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PrivateMessages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PrivateMessageUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PrivateMessages
   * const privateMessage = await prisma.privateMessage.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PrivateMessageUpdateManyArgs>(args: Prisma.SelectSubset<T, PrivateMessageUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PrivateMessages and returns the data updated in the database.
   * @param {PrivateMessageUpdateManyAndReturnArgs} args - Arguments to update many PrivateMessages.
   * @example
   * // Update many PrivateMessages
   * const privateMessage = await prisma.privateMessage.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PrivateMessages and only return the `id`
   * const privateMessageWithIdOnly = await prisma.privateMessage.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PrivateMessageUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PrivateMessageUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PrivateMessagePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PrivateMessage.
   * @param {PrivateMessageUpsertArgs} args - Arguments to update or create a PrivateMessage.
   * @example
   * // Update or create a PrivateMessage
   * const privateMessage = await prisma.privateMessage.upsert({
   *   create: {
   *     // ... data to create a PrivateMessage
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PrivateMessage we want to update
   *   }
   * })
   */
  upsert<T extends PrivateMessageUpsertArgs>(args: Prisma.SelectSubset<T, PrivateMessageUpsertArgs<ExtArgs>>): Prisma.Prisma__PrivateMessageClient<runtime.Types.Result.GetResult<Prisma.$PrivateMessagePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PrivateMessages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PrivateMessageCountArgs} args - Arguments to filter PrivateMessages to count.
   * @example
   * // Count the number of PrivateMessages
   * const count = await prisma.privateMessage.count({
   *   where: {
   *     // ... the filter for the PrivateMessages we want to count
   *   }
   * })
  **/
  count<T extends PrivateMessageCountArgs>(
    args?: Prisma.Subset<T, PrivateMessageCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PrivateMessageCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PrivateMessage.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PrivateMessageAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PrivateMessageAggregateArgs>(args: Prisma.Subset<T, PrivateMessageAggregateArgs>): Prisma.PrismaPromise<GetPrivateMessageAggregateType<T>>

  /**
   * Group by PrivateMessage.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PrivateMessageGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PrivateMessageGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PrivateMessageGroupByArgs['orderBy'] }
      : { orderBy?: PrivateMessageGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PrivateMessageGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPrivateMessageGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PrivateMessage model
 */
readonly fields: PrivateMessageFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PrivateMessage.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PrivateMessageClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  channel<T extends Prisma.PMChannelDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PMChannelDefaultArgs<ExtArgs>>): Prisma.Prisma__PMChannelClient<runtime.Types.Result.GetResult<Prisma.$PMChannelPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  author<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PrivateMessage model
 */
export interface PrivateMessageFieldRefs {
  readonly id: Prisma.FieldRef<"PrivateMessage", 'String'>
  readonly channelId: Prisma.FieldRef<"PrivateMessage", 'String'>
  readonly authorId: Prisma.FieldRef<"PrivateMessage", 'String'>
  readonly content: Prisma.FieldRef<"PrivateMessage", 'String'>
  readonly editedAt: Prisma.FieldRef<"PrivateMessage", 'DateTime'>
  readonly deletedAt: Prisma.FieldRef<"PrivateMessage", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"PrivateMessage", 'DateTime'>
}
    

// Custom InputTypes
/**
 * PrivateMessage findUnique
 */
export type PrivateMessageFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrivateMessage
   */
  select?: Prisma.PrivateMessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PrivateMessage
   */
  omit?: Prisma.PrivateMessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PrivateMessageInclude<ExtArgs> | null
  /**
   * Filter, which PrivateMessage to fetch.
   */
  where: Prisma.PrivateMessageWhereUniqueInput
}

/**
 * PrivateMessage findUniqueOrThrow
 */
export type PrivateMessageFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrivateMessage
   */
  select?: Prisma.PrivateMessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PrivateMessage
   */
  omit?: Prisma.PrivateMessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PrivateMessageInclude<ExtArgs> | null
  /**
   * Filter, which PrivateMessage to fetch.
   */
  where: Prisma.PrivateMessageWhereUniqueInput
}

/**
 * PrivateMessage findFirst
 */
export type PrivateMessageFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrivateMessage
   */
  select?: Prisma.PrivateMessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PrivateMessage
   */
  omit?: Prisma.PrivateMessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PrivateMessageInclude<ExtArgs> | null
  /**
   * Filter, which PrivateMessage to fetch.
   */
  where?: Prisma.PrivateMessageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PrivateMessages to fetch.
   */
  orderBy?: Prisma.PrivateMessageOrderByWithRelationInput | Prisma.PrivateMessageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PrivateMessages.
   */
  cursor?: Prisma.PrivateMessageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PrivateMessages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PrivateMessages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PrivateMessages.
   */
  distinct?: Prisma.PrivateMessageScalarFieldEnum | Prisma.PrivateMessageScalarFieldEnum[]
}

/**
 * PrivateMessage findFirstOrThrow
 */
export type PrivateMessageFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrivateMessage
   */
  select?: Prisma.PrivateMessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PrivateMessage
   */
  omit?: Prisma.PrivateMessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PrivateMessageInclude<ExtArgs> | null
  /**
   * Filter, which PrivateMessage to fetch.
   */
  where?: Prisma.PrivateMessageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PrivateMessages to fetch.
   */
  orderBy?: Prisma.PrivateMessageOrderByWithRelationInput | Prisma.PrivateMessageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PrivateMessages.
   */
  cursor?: Prisma.PrivateMessageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PrivateMessages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PrivateMessages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PrivateMessages.
   */
  distinct?: Prisma.PrivateMessageScalarFieldEnum | Prisma.PrivateMessageScalarFieldEnum[]
}

/**
 * PrivateMessage findMany
 */
export type PrivateMessageFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrivateMessage
   */
  select?: Prisma.PrivateMessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PrivateMessage
   */
  omit?: Prisma.PrivateMessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PrivateMessageInclude<ExtArgs> | null
  /**
   * Filter, which PrivateMessages to fetch.
   */
  where?: Prisma.PrivateMessageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PrivateMessages to fetch.
   */
  orderBy?: Prisma.PrivateMessageOrderByWithRelationInput | Prisma.PrivateMessageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PrivateMessages.
   */
  cursor?: Prisma.PrivateMessageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PrivateMessages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PrivateMessages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PrivateMessages.
   */
  distinct?: Prisma.PrivateMessageScalarFieldEnum | Prisma.PrivateMessageScalarFieldEnum[]
}

/**
 * PrivateMessage create
 */
export type PrivateMessageCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrivateMessage
   */
  select?: Prisma.PrivateMessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PrivateMessage
   */
  omit?: Prisma.PrivateMessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PrivateMessageInclude<ExtArgs> | null
  /**
   * The data needed to create a PrivateMessage.
   */
  data: Prisma.XOR<Prisma.PrivateMessageCreateInput, Prisma.PrivateMessageUncheckedCreateInput>
}

/**
 * PrivateMessage createMany
 */
export type PrivateMessageCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PrivateMessages.
   */
  data: Prisma.PrivateMessageCreateManyInput | Prisma.PrivateMessageCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PrivateMessage createManyAndReturn
 */
export type PrivateMessageCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrivateMessage
   */
  select?: Prisma.PrivateMessageSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PrivateMessage
   */
  omit?: Prisma.PrivateMessageOmit<ExtArgs> | null
  /**
   * The data used to create many PrivateMessages.
   */
  data: Prisma.PrivateMessageCreateManyInput | Prisma.PrivateMessageCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PrivateMessageIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PrivateMessage update
 */
export type PrivateMessageUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrivateMessage
   */
  select?: Prisma.PrivateMessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PrivateMessage
   */
  omit?: Prisma.PrivateMessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PrivateMessageInclude<ExtArgs> | null
  /**
   * The data needed to update a PrivateMessage.
   */
  data: Prisma.XOR<Prisma.PrivateMessageUpdateInput, Prisma.PrivateMessageUncheckedUpdateInput>
  /**
   * Choose, which PrivateMessage to update.
   */
  where: Prisma.PrivateMessageWhereUniqueInput
}

/**
 * PrivateMessage updateMany
 */
export type PrivateMessageUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PrivateMessages.
   */
  data: Prisma.XOR<Prisma.PrivateMessageUpdateManyMutationInput, Prisma.PrivateMessageUncheckedUpdateManyInput>
  /**
   * Filter which PrivateMessages to update
   */
  where?: Prisma.PrivateMessageWhereInput
  /**
   * Limit how many PrivateMessages to update.
   */
  limit?: number
}

/**
 * PrivateMessage updateManyAndReturn
 */
export type PrivateMessageUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrivateMessage
   */
  select?: Prisma.PrivateMessageSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PrivateMessage
   */
  omit?: Prisma.PrivateMessageOmit<ExtArgs> | null
  /**
   * The data used to update PrivateMessages.
   */
  data: Prisma.XOR<Prisma.PrivateMessageUpdateManyMutationInput, Prisma.PrivateMessageUncheckedUpdateManyInput>
  /**
   * Filter which PrivateMessages to update
   */
  where?: Prisma.PrivateMessageWhereInput
  /**
   * Limit how many PrivateMessages to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PrivateMessageIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PrivateMessage upsert
 */
export type PrivateMessageUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrivateMessage
   */
  select?: Prisma.PrivateMessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PrivateMessage
   */
  omit?: Prisma.PrivateMessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PrivateMessageInclude<ExtArgs> | null
  /**
   * The filter to search for the PrivateMessage to update in case it exists.
   */
  where: Prisma.PrivateMessageWhereUniqueInput
  /**
   * In case the PrivateMessage found by the `where` argument doesn't exist, create a new PrivateMessage with this data.
   */
  create: Prisma.XOR<Prisma.PrivateMessageCreateInput, Prisma.PrivateMessageUncheckedCreateInput>
  /**
   * In case the PrivateMessage was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PrivateMessageUpdateInput, Prisma.PrivateMessageUncheckedUpdateInput>
}

/**
 * PrivateMessage delete
 */
export type PrivateMessageDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrivateMessage
   */
  select?: Prisma.PrivateMessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PrivateMessage
   */
  omit?: Prisma.PrivateMessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PrivateMessageInclude<ExtArgs> | null
  /**
   * Filter which PrivateMessage to delete.
   */
  where: Prisma.PrivateMessageWhereUniqueInput
}

/**
 * PrivateMessage deleteMany
 */
export type PrivateMessageDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PrivateMessages to delete
   */
  where?: Prisma.PrivateMessageWhereInput
  /**
   * Limit how many PrivateMessages to delete.
   */
  limit?: number
}

/**
 * PrivateMessage without action
 */
export type PrivateMessageDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrivateMessage
   */
  select?: Prisma.PrivateMessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PrivateMessage
   */
  omit?: Prisma.PrivateMessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PrivateMessageInclude<ExtArgs> | null
}
